### ISSUE TITLE
badge level selection inconsistencies

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1058]
a few issues here:

1. the selection link between badge type and kick-in level is not bidirectional
2. The badge level cost and kick-in level cost can cause confusion due to them not being an equal number
3. The two fields only differ by one additional option, so it may not be necessary to have both.

I don't necessarily have the answers for how this should be fixed yet, but I'm at least recording it so I can think about it later.

**Comment by EliAndrewC** [comment]
1) Excellent point.  This should be easy enough to fix by making it bidirectional.

2) We could fix this by adding both the extra amount AND the base cost to the dropdown.

3) The motivation is that when we ONLY had the dropdown, we had a huge drop in the percentage of people who noticed and selected it.  That's why we added "Supporter" as a separate option on the badge choice page.  (The anthrocon folks didn't like the badge choice page, so they replaced it with this badge choice selection widget at the top of the prereg form, which seems good to me.)

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/pull/1059
