### ISSUE TITLE
MAGStock prereg t-shirt deadline

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1061]
Magstock needs to cut off t-shirt sales after a certain date (near the end of April). The system needs to support this ability.

**Comment by EliAndrewC** [comment]
I assume you mean "near the end of May" since we're already near the end of April.

This is trickier than I thought at first, because the whole concept of donation tiers assumes that each kick-in level is tied into the levels below it.  If there's some period of time in which you can buy a Supporter pack but cannot buy a tshirt, then we'll probably need to remove the tshirt as a donation tier and handle it separately.  On the other hand, if we cut off Supporter registration at the same time, then that's okay.

I've emailed the MAGStock folks to ask them about this.

**Comment by kitsuta** [comment]
Nope. Doc says near the end of April.

**Comment by EliAndrewC** [comment]
Interesting.  Well, I asked them for the deadline date in the email.

**Comment by EliAndrewC** [comment]
Ok, I just heard back and the cutoff date is the same for tshirts as it is for Supporters, so we're fine on that front.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/magstock/commit/6a969e92b56df4e7609ddb5c8584ca21f0fd4688 and https://github.com/magfest/ubersystem/commit/e2c4f247c6791084e04085cf496fa6f51169a126
