### ISSUE TITLE
Personal phone # is not listed as required but is considered required

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1068]
You get a "Please enter a 10-digit phone number" error if you try to register without a cell phone number, but the field is not bold.

By the same token, the emergency contact # field is bolded, but not actually required.

**Comment by kitsuta** [comment]
Which way do we want to fix this? Either changing the check or changing the form is easy.

**Comment by EliAndrewC** [comment]
Whoops.  That sounds like a logic error then.  The actual logic is supposed to be this:
* for normal registrations, the field is not required
* for dealers, the field is required
* for volunteers, the field is required BUT they can click the "I don't own a cellphone" checkbox instead of providing a number
* In situations where the field isn't required the label is normal, but when it's required the label is bold

I'll look into it; the nature of the bug will affect where the fix should go.

**Comment by kitsuta** [comment]
Should the EC number be required?

**Comment by EliAndrewC** [comment]
It's always required for MAGStock.  It's something we can make not required and/or eliminate it entirely for other events in plugin code.

**Comment by kitsuta** [comment]
Right, my point being, it's not actually checked in the code. :)

**Comment by EliAndrewC** [comment]
Ohhh, whoops!  That should also be fixed.  I thought I had added that back in, haha.

**Comment by EliAndrewC** [comment]
Fixed in https://github.com/magfest/ubersystem/pull/1069
