### ISSUE TITLE
transfer email text incorrect for magstock

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1097]
says "badge" and has a bunch of reference to magprime specific stuff.  probably need to just override the email template

> ... should have no trouble picking up the badge at our registration desk.

> Badges are not mailed out before the event, so your badge will be available for pickup at the registration desk when you arrive at MAGFest. Simply bring a photo ID to the registration desk, where you'll be provided with your badge. If you ordered bonus items such as a ribbon, t-shirt, or supporter package, you can pick those up at our merchandise booth. The location and hours of the registration desk and merchandise booth will be e-mailed prior to the event.

**Comment by EliAndrewC** [comment]
Whaaaaa - we totally do have a template override for this:
https://github.com/magfest/magstock/blob/master/magstock/templates/emails/reg_workflow/attendee_confirmation.html

Here's the wording from that page:

> No registration materials are physically mailed before the event, so you should check in at the registration desk when you arrive at MAGStock. Simply bring a photo ID to the registration desk, where you'll be provided with your admission wristband. If you ordered bonus items such as a t-shirt or supporter package, you can also pick those up at the registration desk. The location and hours of the registration desk will be e-mailed prior to the event.

I specifically tested this on my test server before we launched prereg, so I'm not sure what happened :(

**Comment by EliAndrewC** [comment]
Derp, never mind - I totally missed where you explicitly said that it's the badge transfer email.  Derp.

I agree this seems sensible.  Since this wording is in two different places, we might want to break that out into a sub-template which is included by both emails, both because it'll be easier for plugins to override and because it's generally a bad idea to have the same thing copy/pasted in two places (since then when we update it we need to remember to do so twice, etc).

**Comment by kitsuta** [comment]
Magstock is over, so this issue is no longer relevant.
