### ISSUE TITLE
ubersystem can't be used offline - depends on a lot of hotlinked JS

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1131]
So, it's not a huge deal but, one of our use cases remains that ubersystem should remain functional if it's being run off a local server and the internet dies (13 years in and we still can't seem to solve this 100% of the time).  For Magstock, this is still a realistic use case.

I see a few things like in base.html where we directly link to particular javscript files:
```
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
```

Do we have a method we're moving towards to download these locally and save them in git, or pull them down and cache locally as part of the build process?  I'm not much of a frontend dev, so not sure what the right way to handle this kind of stuff.   What do you guys think?

**Comment by kitsuta** [comment]
These scripts can probably be added to the repo easily, but we need an
"offline switch" that does things like:

* Disable Google autocomplete for full addresses
* Remove "Pay with credit card now" option from kiosks
* Disable prereg on the cloud server
* Disable "loading slow" screen which is really only for users who have
strange browser configurations

**Comment by EliAndrewC** [comment]
The two JS files that @binary1230 mentioned are only there for compatibility with versions of IE older than IE9.  Personally I'm okay just flat out not supporting browsers that old, but the Anthrocon folks added those links and I didn't see any reason to rip them out, since they're wrapped in an if block that ensures they don't even get loaded in other browsers, so they're not doing any harm to our page load times.

As @kitsuta points out, there are currently areas where an internet connection is inherently required given the nature of the task, e.g. Stripe.  I'm not sure if that's within the scope of this ticket or not.

**Comment by binary1230** [comment]
With internet going out so too does Stripe, though, we can usually are still in a scenario where a backup payment method like Square or traditional merchant services can fill in, and the rest of uber is working OK fully offline.

Ah, yea didn't notice the context of those 2 files. Cool.  Just thinking if we had any other ones like that, I know a lot of apps do the CDN hotlink thing for jquery/etc.

**Comment by EliAndrewC** [comment]
> Ah, yea didn't notice the context of those 2 files. Cool. Just thinking if we had any other ones like that, I know a lot of apps do the CDN hotlink thing for jquery/etc.

I believe that I've already replaced all of the hotlinking for those apps.  To the best of my recollection, those were all cases where we had standalone Angular apps for things like shift signups and hotel room assignments and tabletop checkout.  I've since replaced those to just include our bower-managed consolidated Javascript file, since that way everything gets the benefit of our new JS dependency management.

**Comment by EliAndrewC** [comment]
Reopening because the PR that @kitsuta just merged only addresses some of the things described in the comments above.

**Comment by kitsuta** [comment]
Hm. So there's no Google autocomplete right now, thus no reason to disable it. And disabling pre-reg on the cloud servers seems... kind of impossible to do from the onsite server? Was there any hotlinked stuff that I missed?

**Comment by EliAndrewC** [comment]
I don't think there's any more hotlinked stuff.  The main thing from your original list which isn't addressed is 'Disable "loading slow" screen which is really only for users who have strange browser configurations', but honestly I'm somewhat indifferent to that one, so if you want to get rid of it as a requirement and re-close this then that's fine with me.

**Comment by kitsuta** [comment]
That actually was in there, at https://github.com/magfest/ubersystem/pull/1539/files#diff-6dd88784d1395480e2c7fc071e9f0eeeR165. I decided to simply only show the slow-loading screen if `PRE_CON` was true, since again, that's its intended usage.

**Comment by EliAndrewC** [comment]
Oh cool, glad to have this closed out then!
