### ISSUE TITLE
Add address field to registration form

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1165]
Prompt the attendee to get entire their full mailing address as of August 28, 2015. 

Add a note that we MAY be mailing badges, but have not fully committed to it yet.

**Comment by kitsuta** [comment]
I have concerns about this, particularly since we're not even necessarily going to use people's addresses.

I'd like to give folks the ability to opt-in to badge mailing, so they don't have to provide their address to register. That way we're collecting less personal data, and we'd get a good idea of how many people actually want badges mailed to them.

We could even present it as a voting mechanism. Word it something like,
> As MAGFest grows, we are considering mailing out badges to help reduce overhead at the event. However, mailing out badges has both advantages and disadvantages, so we'd like to hear from you! If you'd like to have your badge mailed to you, simply check this box and enter your address - if enough people vote yes, we'll mail out your badge for this MAGFest Classic!
>
> Remember, if your badge is mailed to you, it's just like a ticket for a concert - losing it means that you have to buy another badge, and if we're sold out of badges, you won't be able to get a replacement! No exceptions. Seriously.

**Comment by EliAndrewC** [comment]
I'm gonna ignore this one for now, since I share @kitsuta's concerns and we're super-pressed for time.  Are we really gonna revamp our hotel signup procedures AND run this MagClassic AND launch MagPrime prereg AND figure out how to mail out badges in the next 2 months?  Not to mention the warehouse move, etc... honestly I think this is a pipe dream for MagClassic and unless someone objects I'm gonna just close this.
