### ISSUE TITLE
Enable group registration

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1166]
Price point TBD

**Comment by earl7399** [comment]
Why would we keep groups?  I thought their purpose was to boost attendance,
which we clearly don't need any longer.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by nickthenewbie1** [comment]
I was not satisfied with 8.5 registration numbers by any stretch of the imagination (we sold about half our cap), so I'd rather not take that risk again.

**Comment by EliAndrewC** [comment]
MagClassic was way UNDER-attended last year, so we definitely want groups for MagClassic this year.  Hopefully within a year or two of more MagClassic events they'll go away and we'll just charge everyone full price.

**Comment by earl7399** [comment]
IMO, we didn't advertise it nearly enough last year, nor did we start early
enough.  It will be interesting to see what the #s are this year.  HIT THE
CAP!

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
I'm fine with groups.

In general, groups themselves are less and less of a problem - we've solved a lot of the logistic headache they used to give us. Or at least, I think we did.

I'm still in favor of changing how groups work so that, instead of a per-badge discount, each badge in a group gets a donation-level perk.

**Comment by kitsuta** [comment]
I'm fine with groups.

In general, groups themselves are less and less of a problem - we've solved a lot of the logistic headache they used to give us. Or at least, I think we did.

I'm still in favor of changing how groups work so that, instead of a per-badge discount, each badge in a group gets a donation-level perk.

**Comment by EliAndrewC** [comment]
> I'm still in favor of changing how groups work so that, instead of a per-badge discount, each badge in a group gets a donation-level perk.

That does seem like a great way to keep the good stuff about groups as we start to phase out the discounts over the next several years for MAGFest and also hopefully MagClassic.

**Comment by kitsuta** [comment]
Darn right!

The main code requirement for that is to separate donation levels and amount_extra, so that we can give people donation levels for free. I technically have that working in anthrocon-staging, but we'd want to write a better version of the feature for MAGClassic if possible.

**Comment by EliAndrewC** [comment]
PR to fix group prereg issues at https://github.com/magfest/ubersystem/pull/1201/files
