### ISSUE TITLE
Set base badge price

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1170]
Price TBD

**Comment by kitsuta** [comment]
These aren't really GitHub tickets so much as configuration options and decisions to be made for launching MAGFest Classic.

It's good that we have them written down, but I'd really like to move to a more project-management-oriented system so that we can just keep actual code-related issues to GitHub.

**Comment by EliAndrewC** [comment]
Fair enough, though for now it's super-useful to me to be able to look at a single TODO list.  Maybe a good compromise is to have a single Github ticket that's "all config changes" and it just links to Phab or wherever.

**Comment by EliAndrewC** [comment]
Also, I'm assuming that we're doing $50 / $60 / $70 for the price progression for starting / August / September.  We can always change it later, but that's what's implemented in puppet.
