### ISSUE TITLE
Separate  badge type buttons into different groups

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1217]
Right now the buttons read:

ATTENDEE  |  GROUP LEADER  |SUPPORTER

I propose they change to be formatted like this:

Registration type: SINGLE ATTENDEE       |    GROUP LEADER 

Badge Level: STANDARD ATTENDEE  | ADD A TSHIRT   | SUPPORTER PACKAGE

**Comment by kitsuta** [comment]
I vote that we make this separation in the master repo, though we'd customize the actual badge levels via the magclassic plugin.

**Comment by EliAndrewC** [comment]
Seems reasonable.

**Comment by EliAndrewC** [comment]
@kitsuta: this is assigned to you, but I'm gonna grab this one since it's one of the last things we have to finish up before launch and I think I can get it knocked out pretty quickly today.  If you've already written some code for this and/or want to finish it yourself then let me know and I'll back off and tackle something else.

**Comment by kitsuta** [comment]
Whoops, this is actually part of https://github.com/magfest/ubersystem/pull/1223 - I just forgot to link them.

**Comment by EliAndrewC** [comment]
@kitsuta pointed out a few minutes ago that there's a partial fix for this in 
https://github.com/magfest/ubersystem/pull/1223
which moves a lot of the config to the backend.

Some requirements to note which weren't mentioned in this issue's description but which came out of the other discussion:
- we want the badge type selector to show up on other pages such as the badge confirmation page and the unassigned group badge claiming page
- in those cases we do not NOT want the "registration type" field to show up; that should only be displayed on the main prereg form, since that's the only place where we're actually presenting a choice
- on the badge confirmation page, we only want the "badge type" selector to show up if they haven't already selected a donation level; once they've selected and paid for a particular kick-in level, one or more of the options will no longer be valid, so it's probably simplest to simply not display that badge row
- we'll need to decide what to do about the at-the-door reg form; it sounds as if we're going to be merging the prereg and at-the-door forms so that decision can probably wait until that gets settled

I'm willing to take a stab at implementing all of this today.  With that being said, my solution will probably end up being in Javascript, using the Magstock-style "you can override behavior in the plugin", because my intuition is that this is the simplest way to meet all of the above requirements.

The existing PR also has a config section so that plugins can use configuration to define extra donation levels.  I'm inclined to leave that off for now, for 4 reasons:
- We don't need it for MagClassic.
- It requires additional puppet work.
- The existing implementation would need to be extended to handle defining levels whose order is intermixed with the default levels.
- The existing implementation would need to be extended to handle cases where an item requires custom Javascript.  (Admittedly, this will only be a real requirement for MAGFest events if we move Season Supporters out of the core repo and into the MAGFest repo.  That's something I definitely want to do, but we could punt on that for now if we wanted.)

**Comment by kitsuta** [comment]
Not displaying the badge row when they've selected a kick-in level means that they can't easily upgrade their badge further. Say they buy a t-shirt and want to go back and upgrade to a Supporter badge - the row will be gone because they bought a t-shirt, so it won't be obvious how to upgrade further.

**Comment by EliAndrewC** [comment]
I wouldn't have said "not obvious" since the donation row is still right there.  Still, you might be right and people would just be confused.  I can take a stab at implementing that if you think it's important.

In the case where someone has selected a level not on the badge row, I assume we'd just select the lowest level they did select and not show the others.

**Comment by kitsuta** [comment]
Hm, yeah, that seems appropriate. And then just not show any levels lower than the one they have? That's not difficult to do in the current PR, though it sounds you like you want to take a different approach.

**Comment by nickthenewbie1** [comment]
If possible, I'd like to kill the drop down altogether in favor of the
buttons

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by EliAndrewC** [comment]
Do you mean just for MagClassic, or for all events?  Last year MAGFest's donation tiers were:
- $5 ribbon
- $10 button
- $20 shirt
- $60 Supporter package
- $100 USB drive
- $160 Season Supporter
- $200 throwing disc (actually I can't remember if we went through with that, but it's in my notes)
- $500 Lightsuit

I'm not sure we want to eliminate all levels which don't get columns in the Badge Type form up top, and I don't think we want all of those levels there.

**Comment by nickthenewbie1** [comment]
I have some ideas for button replacements that might be feasible. Either
sliders, or perhaps less levels.

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

Do you mean just for MagClassic, or for all events? Last year MAGFest's
donation tiers were:

   - $5 ribbon
   - $10 button
   - $20 shirt
   - $60 Supporter package
   - $100 USB drive
   - $160 Season Supporter
   - $200 throwing disc (actually I can't remember if we went through with
   that, but it's in my notes)
   - $500 Lightsuit

I'm not sure we want to eliminate all levels which don't get columns in the
Badge Type form up top, and I don't think we want all of those levels there.

—
Reply to this email directly or view it on GitHub
<https://github.com/magfest/ubersystem/issues/1217#issuecomment-122705864>.
