### ISSUE TITLE
MAGClassic 2015: Schedule

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1233]
While there are a lot of open issues around Scheduling - and how we can make it better, clearer and easier to link in required staff etc etc.... for MAGClassic
https://classic.uber.magfest.org/uber/schedule/

Do we need all the different options across the top?
Are we going to have 5 panel rooms and 2 MAGES rooms?
Plus Forums, Autographs, Arena, 3 different Arcade tournaments going at once, NGA Tournaments (Are they coming to Classic?) etc etc...

If we can clean up that section, they we would have a better idea of what it takes to work on the other outstanding scheduling tickets... especially for Classic which is suppose to be our test bed Festival.

**Comment by kitsuta** [comment]
This is technically a set of config options, but removing them is relatively painful, as they're stored in the database. So this will require both a config change and sysadmin intervention.

**Comment by kitsuta** [comment]
I've added this to the config, but before we can really call this fixed, we need a list of MAGClassic locations. @binary1230 any ideas?

**Comment by binary1230** [comment]
perhaps we can look at last year's event_locations and go from there, that'll be a good starting point.  not too much is changing in terms of public-facing layouts this year.  this is from last year's 8.5 uber instance:

```
EVENT_LOC_OPTS = enum(
    PANELS_1 = 'Panels 1',
    PANELS_2 = 'Panels 2',
    PANELS_3 = 'Panels 3',
    LAN = 'LAN',
    ARCADE = 'Arcade',
    CONCERTS = 'Concerts',
    TABLETOP = 'Tabletop',
    TABLETOP_CCG = 'Tabletop CCG',
    CONSOLE_ROOM = 'Console Room',
    OUTDOORS = 'Outdoor Events',
    JAMSPACE = 'Jamspace',
    CHIPTUNES = 'Chiptunes',
    REGISTRATION = 'Registration',
    HORIZONS = 'Horizons'
)
```

I -think- that's pretty accurate still, might need to add the computer museum

important note: this new setting was not added to classic.uber.magfest.org, I assume intentionally because of your comment, just wanted to make sure.
