### ISSUE TITLE
Deactivate or remove Staff Suite Volunteer Email

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#1234]
Please deactivate or remove the email that sends out when people request to volunteer in Staff Suite.

Thanks!

**Comment by binary1230** [comment]
pretty sure this is currently not included in magclassic because it's part of this plugin here which we are not using:
https://github.com/magfest/magprime_emails/blob/master/magprime_emails/templates/emails/food_volunteers.txt

I'm going to close this issue then, @JennyTruss if the link above is not the email you were talking about, please re-open this issue.
