### ISSUE TITLE
fix dealer registration

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1244]
Dom's mental notes on how to do this:

1) in configspec.ini change dealer_reg_public to:
```python
dealer_reg_public      = string(default="%(dealer_reg_start)s")
```

2) fix the dealer reg form UI.  probably make 'dealer' be another of the 2 existing buttons (group, single).

**Comment by kitsuta** [comment]
Can I get confirmation that we actually do want "Dealer" as another badge_type button, and not a separate page like it's been in the past? We can do either way pretty easily, I just need to know which way Marketplace prefers.

**Comment by EliAndrewC** [comment]
In the past Danielle has expressed a strong preference for keeping it separate.

That would certainly be simpler, because we've also decided in the past to not allow kick-ins for our dealer applications.  Because the application process is so competitive, we've wanted to avoid anyone feeling like we were saying, "Pretty nice dealer application you've got there, be a shame if it didn't get approved... hey, want to kick in some extra money?"  That's obviously not what we want.

Obviously we could remove that row if dealer registration was selected, so this probably isn't a huge deal, and I'll defer to whatever Danielle ultimately wants, but I just wanted to mention it.

**Comment by kitsuta** [comment]
I know that Anthrocon's Dealer Den head also wanted this to be a separate form.

Based on the data we have, I'd lean towards keeping it a separate page like it's been in the past. The reasoning behind it is solid - we just have to fix the tags for that "Dealers sign up here" link.
