### ISSUE TITLE
re-enable client-side sorting for various pages

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1273]
notably, replace the functionality from #1266, which is server-side sorting, with client-side sorting.  this is a speed optimization.

@kitsuta thinks that this functionality existed but was then removed by accident, so in theory it's a matter of finding out where it was removed from and then re-enabling it.

**Comment by kitsuta** [comment]
For reference, this is what Anthrocon's version of RAMS looks like:

![image](https://cloud.githubusercontent.com/assets/7198215/8912375/87789e04-3460-11e5-85ac-3370496f70e2.png)

Note the arrows next to every column. They let you sort each column instantly.

The arrows are gone from master, but we're not really sure why.

**Comment by binary1230** [comment]
huh. oh yea i remember those.

**Comment by nickthenewbie1** [comment]
Martketplace is pressing on having this done asap, as it's interfering with their process.

**Comment by binary1230** [comment]
will maybe try and hit this today if possible.

**Comment by kitsuta** [comment]
We don't have FooTable installed.

That'd do it. :stuck_out_tongue:

**Comment by earl7399** [comment]
Oy.  Good catch!

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
OK, so we install FooTable (hence me deleting my earlier comment), _but_ FooTable has its own plugins - which definitely don't get installed. One of those plugins is making sorting work.

**Comment by thaeli** [comment]
Yes, sorting is in a FooTable plugin. I would prefer us to convert to this plugin though, since it will work better for our full spectrum of needs going forward: http://datatables.net/

(See examples at http://datatables.net/examples/server_side/simple.html for how to set it up with server side JSON / client side parsing, which will give us the best of both server and client side pagination etc.)
