### ISSUE TITLE
MAGClassic 2015: Search Function on Staffer page

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1293]
On the page:
https://classic.uber.magfest.org/uber/registration/staffers

The Search box function doesn't work, you can enter data, but clicking on the search glass results in nothing happening. 

 Control F is a work around for this and is ok as long as the staffer page stays a single page of results, but I don't know how many entries will make that be multiple pages.

**Comment by EliAndrewC** [comment]
The main reason why we have a search box on that page is because the search box checks fields which aren't visible and therefore cannot be found with Ctrl+f.  For example, if you wanted to find all volunteers who had the word "belligerent" in their admin notes, you could type that word into the search box.  So definitely a good thing to get this fixed even if we don't need it for the normal use case of "find someone by name".
