### ISSUE TITLE
Add Sqitch and apgdiff to installation process

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1295]
You can install Sqitch using `cpan App::Sqitch DBD::Pg`. Installing apgdiff is just a matter of `apt-get install apgdiff`.

Cpan may need extra memory or swap for the installation process to complete correctly - we ran into problems on the staging server due to lack of memory.

**Comment by binary1230** [comment]
sqitch install doesn't work on <512mb of RAM, so need to add swap.

this is pretty easy, puppet/etc just needs to run these commands: https://gist.github.com/binary1230/253a5303ea2eb6102116

related to https://github.com/magfest/ubersystem-deploy/issues/4

**Comment by kitsuta** [comment]
Oh right, we should also add this set of commands to the installation process:
```
sudo su - postgres
cd ${uber_path}/plugins/uber/
sqitch deploy master-base --log-only
```

That part requires https://github.com/magfest/ubersystem/issues/1296

**Comment by binary1230** [comment]
also, I think this is one component of a larger discussion of how we should handle DB migrations in a more automatic way.  we need to dig into sqitch a bit but I think it already does the heavy lifting on the hard parts.

from a devops perspective it would be cool if the situation was like this:

> magbot deploy to production
```
magbot: HEY I detected a required database migration is detected with the new changes, type 'migrate_db' if you're sure you want to confirm
```

> magbot deploy to production migrate_db
```
magbot: OK. doing the DB migration.  
offlining site for maintenance....
backing up DB first...
deploying latest code....
migrating... 
successful migration!
bringing site back up....
done!
```


For how we actually do this, the deploy stuff could run the 'sqitch status' commands that tell us if the DB is up to date or requires a migration.  I am pretty sure (though not certain) that sqitch adds metadata info to the pgsql DB in order to track this stuff, so it's doing the heavy lifting for us.

This part is a lot of work but I think ultimately straightforward.  There will have to be some careful thought about interaction with plugins / DB/etc when plugins override columns.  

Also, we'll have to think about how this fits into the docker universe.

**Comment by binary1230** [comment]
But anyway, we can for sure sooner than later install sqitch as part of puppet and still run it manually.  My unreachable end-goal is that all deployment stuff is fully automated including DB migrations.  My ideal is that if we have to SSH in, we're doing it wrong.

**Comment by kitsuta** [comment]
Sqitch is gone, so this is no longer relevant.
