### ISSUE TITLE
Volunteer Checklist Email...

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1372]
"MAGClassic shifts available "

Rename- Subject line: MAGClassic Volunteer Checklist (please complete)

Body of Email:

Test,

Thanks for signing up to volunteer at MAGClassic!  You're currently assigned to the Consoles department, but let us know if you'd also like to work in any other departments.

You can complete the checklist at:
https://stage.uber.magfest.org/uber/signups/login

This checklist includes: 
-Confirming that you are coming to MAGClassic.
-Any Food restrictions you might have for our Staff Suite
-Your T-shirt size for our Merchandise department
-Hotel room request (Nights and roommate request)
-Shift Signup information.

If you have trouble logging in, you can verify/update your personal information at https://stage.uber.magfest.org/uber/preregistration/confirm?id=df143dd1-e3be-41c5-90d6-5dea6f902021

You can add / drop / change your shifts anytime until 11:59pm EDT on Thursday, Sep 10.

Please let us know if you have any questions.

Thank You,
Stops@magfest.org
Staff Operations: MAGFest Inc.
http://www.magfest.org

**Comment by EliAndrewC** [comment]
I did this, but with 2 exceptions:

1) Changing the email subject is slightly more work, since that has to be changed in two repos.  If you think it's really important I can make a new PR into the main repo as well or something equivalent, but in the interest of time I left the subject as-is.

2) I moved the date they can add/drop shifts back 2 days, because Uber may go offline around that time, depending on how we do our on-site hosting of Uber.
