### ISSUE TITLE
new attendee with volunteer ribbon is not marked as staff

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1404]
to repro:
1) goto registration admin form
2) set placeholder true, first name, last name, and ribbon=volunteer

expected:
attendee.is_staffing == True

actual
attendee.is_staffing == False

--------------

I've written a unit test which repros this behavior, will link in a sec. There is some existing test coverage but it doesn't seem to cover the case where ```attendee.is_new == true```

I think the right fix is to change a line to def _staffing_adjustments(self) like this:

```python
if self.badge_type == c.STAFF_BADGE or self.ribbon == c.VOLUNTEER_RIBBON:
            self.staffing = True
```

**Comment by binary1230** [comment]
this was discovered when Brent added someone who is attendee+volunteer ribbon and the automated email wasn't being sent out because ```StopsEmail()``` checks if ```attendee.is_staffing == true```

**Comment by thaeli** [comment]
Is this the best solution? Perhaps we should just expose is_staffing directly instead of relying on a specific ribbon?

**Comment by EliAndrewC** [comment]
> Is this the best solution? Perhaps we should just expose is_staffing directly instead of relying on a specific ribbon?

To clarify, there is a ``staffing`` boolean column which is exposed directly.  However, we also have a Volunteer ribbon, and a Staff badge.  Because of this, we have several adjustments we do, e.g.
- if an admin marks someone as getting a Volunteer ribbon, we also set the staffing field to true, because they clearly meant for that person to be a volunteer, and vice versa
- ditto for if an admin marks someone as having a Staff badge
- similarly, if someone unchecks the staffing checkbox, we also remove their volunteer ribbon even if the admin didn't explicitly do that

There are a bunch of ease-of-use adjustments like this.  Apparently one of those cases was missing for new staffers.
