### ISSUE TITLE
make sitemap functionality list pages in plugins

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1428]
When Eli updates the Staff Hotel information, we lost the links to that information in the site map.
I would like to have the following links added back to Uber so they are easier to get to and I don't have to rely on bookmarks.

Site map from Prime as an example:
https://prime.uber.magfest.org/uber/accounts/sitemap

I would also like to add the following links:
https://classic.uber.magfest.org/uber/hotel_assignments/ordered

https://classic.uber.magfest.org/uber/hotel_assignments/#/

Brent

**Comment by EliAndrewC** [comment]
My highest priority at the moment is getting the panel form integrated into Uber, then importing the M13 staffers into the Mag2016 database so we can launch prereg.  After that, this will be the next thing I do.

**Comment by binary1230** [comment]
brainstorming on this issue a bit.

is the more generic reason this is not happening because links to pages from site_sections.py in plugins are not counted in whatever does the enumeration of the site map links?  I think we had discussed that once

**Comment by EliAndrewC** [comment]
> is the more generic reason this is not happening because links to pages from site_sections.py in plugins are not counted in whatever does the enumeration of the site map links? I think we had discussed that once

Correct.  Currently the implementation looks in the ``site_sections`` folder instead of just looking at ``cherrypy.tree.apps``.  Until we split things out into plugins there was no difference, so I just happened to implement it the first way.  Now that there IS a difference we need to change it to work the latter way.

This is on my list of "soon" issues which I expect to get to after the MIVS stuff settles down.

**Comment by bds002** [comment]
Updating this to the Prime Version of the Hotel links... although the MIVES, Tourneys and MAGES stuff should all also be in the Site Map for the appropriate users.

Hotels:
https://prime.uber.magfest.org/uber/hotel/requests (Roommate Request)
https://prime.uber.magfest.org/uber/hotel_assignments/#/ (Rooms Setup)
https://prime.uber.magfest.org/uber/hotel/no_shows
https://prime.uber.magfest.org/uber/hotel/index (Eligible by Department)
https://prime.uber.magfest.org/uber/hotel/hours

**Comment by binary1230** [comment]
@bds002 quick FYI: we don't actually need an explicit list of URLs to be added to the sitemap.  RAMS is can look at itself and tell us what pages it knows about, and that info is the sitemap.

currently, the way it does this inspection only lists pages in core RAMS, and can't detect pages that are part of plugins (i.e. hotel, mivs, etc).  what we need to do is modify the inspection code and then all the plugin pages will show up automatically in the site map.

this wasn't a problem in the past because we only had pages in core RAMS, and there were no plugins.  now that we started breaking things out into lots of plugins, it's an issue.

as Eli pointed out, the fix is actually probably fairly simple in the end.

**Comment by EliAndrewC** [comment]
Right.  Just gotta get through the work for the MIVS, Panels, Attendee Tournaments, and Bands plugins and then I'll have time to get started on this stuff.  Almost certainly sometime in December.

**Comment by bds002** [comment]
I think this is something we can bump to the MAGLites team.  
https://jira.magfest.net/browse/INC-495
