### ISSUE TITLE
hotel room assignments not sticking / tracking code possibly not working

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#1436]
Hi! I just sent Code an email but here's good too. We have a few staffers who said that they filled out the hotel space form before the deadline but they're not showing up as doing so in uber. Is it possible they just didn't do it right or could there be a real bug here? Could you please check?

No pressure, but this is pretty mission critical as the hotel wanted the staff list tomara, Tues, on the 1st. We'll give them what they can but hopefully we can work this out.

Thank you!!!!!!
Steph

**Comment by EliAndrewC** [comment]
It looks like a fairly small number of people were affected by this... however it is troubling.

Unfortunately, our Feed of Database Changes seems to now have a bug where it sometimes doesn't record the foreign keys of models when they're first saved.  Which means that for ``HotelRequests`` objects, as they're being saved, we have some records of them which have all of the data except which attendee the request is for.... which is fairly important for a number of reasons.  Bleh.

I've checked the database snapshot from before we did the plugin upgrade, and none of the people who are saying they filled out the hotel requests are in the dump.  One of those people clearly never filled out the checklist, but one of them clearly did, so it looks like their hotel requests just got completely deleted somehow... which shouldn't even be possible.

Normally this is where I'd go through the Feed of Database Changes to figure out whose records were deleted, but the bug I mentioned above makes that pretty much impossible.  So I'm not even sure what to do at this point :(

Anyway, of the four people who have claimed to have filled out the checklist:
- one of them looks like they signed up for shifts as an admin and never actually filled out the checklist
- one of them has clearly never logged in to fill out any part of the checklist
- one of them isn't even in the database in the first place
- one of them looks like they probably did fill it out, but it somehow got messed up

So I don't think this is a widespread problem, and the resolution for this issue is going to mainly need to be to fix the underlying issue with the Feed of Database Changes so that we can have a more complete record of this sort of thing.

**Comment by StephPrader** [comment]
I'm sorry about the bug you found but I'm glad it's not a widespread issue.
We're able to take care of these few very easily. Thank you Eli! Thank you
Dom too! ^_^
Steph

On Mon, Aug 31, 2015 at 11:47 PM, Eli Courtwright <notifications@github.com>
wrote:

> It looks like a fairly small number of people were affected by this...
> however it is troubling.
>
> Unfortunately, our Feed of Database Changes seems to now have a bug where
> it sometimes doesn't record the foreign keys of models when they're first
> saved. Which means that for HotelRequests objects, as they're being
> saved, we have some records of them which have all of the data except which
> attendee the request is for.... which is fairly important for a number of
> reasons. Bleh.
>
> I've checked the database snapshot from before we did the plugin upgrade,
> and none of the people who are saying they filled out the hotel requests
> are in the dump. One of those people clearly never filled out the
> checklist, but one of them clearly did, so it looks like their hotel
> requests just got completely deleted somehow... which shouldn't even be
> possible.
>
> Normally this is where I'd go through the Feed of Database Changes to
> figure out whose records were deleted, but the bug I mentioned above makes
> that pretty much impossible. So I'm not even sure what to do at this point
> :(
>
> Anyway, of the four people who have claimed to have filled out the
> checklist:
>
>    - one of them looks like they signed up for shifts as an admin and
>    never actually filled out the checklist
>    - one of them has clearly never logged in to fill out any part of the
>    checklist
>    - one of them isn't even in the database in the first place
>    - one of them looks like they probably did fill it out, but it somehow
>    got messed up
>
> So I don't think this is a widespread problem, and the resolution for this
> issue is going to mainly need to be to fix the underlying issue with the
> Feed of Database Changes so that we can have a more complete record of this
> sort of thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magfest/ubersystem/issues/1436#issuecomment-136569004>
> .
>



-- 
__
Stephanie Prader
Division Director, Programming
MAGFest
www.magfest.org
703-964-6707

**Comment by kitsuta** [comment]
I strongly suspect whatever's causing the FODC to bug out is probably wreaking havoc elsewhere, and possibly even the cause of these checklists getting lost. Losing the attendee UUID in the middle of a database update seems like it could cause an awful lot of problems.

**Comment by EliAndrewC** [comment]
> Losing the attendee UUID in the middle of a database update seems like it could cause an awful lot of problems.

I *think* that what's happening is not that the saves are getting messed up, but that the ``Tracking`` table code isn't properly handling all of the ways that a foreign key can be set.  Consider how the ``HotelRequests`` code is defined.  There are basically three ways that we could associate a ``HotelRequests`` instance with an ``Attendee``:

```python
req.attendee = attendee
req.attendee_id = attendee.id
attendee.hotel_requests = requests
```

The ``Tracking.track()`` method looks at objects which are about to be saved and iterates over their column values and saves them to the ``data`` column.  It further detects which fields are foreign keys and then saves those separately to the ``links`` column for easy querying.

I believe that what's happening is that in the above three examples of setting the foreign key relationship, the ``Tracking.track()`` method supports the section example but we started doing things according to the first example partway through the year but we didn't realize that ``Tracking.track()`` needs to be updated to handle this case.

So I don't *think* that the Tracking bug represents a real problem with how things are being saved, just that it's messing up our Feed of Database Changes.  I can confirm that later this week when I have a little more time.

**Comment by binary1230** [comment]
we should prob break this into 2 different issues, one about the hotel stuff not sticking, one about the tracking code not dealing with FK's correctly.

**Comment by bds002** [comment]
What is the status of this and the plugins being fed back to the list of DB changes?
There have been 15 or so rooms created for MFest2016 and they all seem to be recorded in the Feedback of DB changes.

**Comment by EliAndrewC** [comment]
Some stuff will show up there and other stuff won't, and I haven't had time to figure out why yet.

Sometime around the beginning of December I should be mostly done with the department-specific plugin work for folks like MIVS and Panels, so I'll be able to swing back around to this and several other tickets hwich have been marked with ``soon`` for the past several months :(
