### ISSUE TITLE
[2016]Kick in level display on update attendee info badge

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1464]
When an attendee views the link to update their information, their kick-in level is not highlighted, and they're able to select a kickin level lower than what they purchased (though I have not tried saving after selecting a lower level).

**Comment by kitsuta** [comment]
They can definitely select a lower kick-in level, which should be fixed. However, a quick glance at a random attendee shows that their kick-in level is properly highlighted.

**Comment by kitsuta** [comment]
OK, it turns out the second problem was only happening for kick-in levels about $100, and it was the result of this block here:
```python
while (window.BADGE_TYPES && BADGE_TYPES.options[0].extra < {{ attendee.amount_extra }}) {
            BADGE_TYPES.options.splice(0, 1);
        }
```

When the attendee had a kick-in level greater than any of the badge type buttons, this block would remove them _all_, which caused errors in that block and elsewhere in the JS (since it was not built for the buttons being removed but `window.BADGE_TYPES` being still there). As usual, the errors caused other parts of the JS to stop working.
