### ISSUE TITLE
why did rams1 run out of space

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1525]
Might be more of an ops issue, but:

rams1 onsite uber ran out of space from running out of inodes (file handles), and the culprit was it was creating TONS of sessions files (like > 65k unique session files).  When these exhausted the available inode capacity of the system, the logfiles filled up with spam about it, and then we ran out of space.  So we ran out of inodes AND disk space, which is impressive : )

My only slight hunch (and it may be a total red herring) is that the API calls (which were being used heavily for LAN barcodes and maybe staff suite) might have resulted in erroneous unique sessions being created.  Not sure, that's my first guess at what might have changed since last time.

**Comment by binary1230** [comment]
oh hey that was easy.  I just tested it and each API call creates 3 unique new session files.

not saying this was the only cause (cause... not sure how even heavy usage would create 65k session files), but definitely an issue.

**Comment by binary1230** [comment]
wait dumb, it's not 3 sessions, I was just doing 3 calls.

But, legit, every API call creates ONE unique session.

**Comment by earl7399** [comment]
Assuming there was a decent amount of testing by the BC and FP folks, I can
see still see this happening.

How are the sessions *supposed* to be closed / go away?  Is there a way to
force that (e.g. lack-of-input timeout)?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

On Tue, Sep 22, 2015 at 9:26 AM, Dominic Cerquetti <notifications@github.com

**Comment by binary1230** [comment]
Eli can talk more about this than I can, but, sessions in other apps typically persist either until you log out or until some timeout period (like a few hours or a day) passes.  In uber, I don't think we timeout sessions at all, so they stick around forever.

In the case where a ton of sessions are getting created at once though, even if there was a reasonable timeout like a few days, it could still get overwhelmed because it could create sessions faster than the app is destroying them.

**Comment by binary1230** [comment]
Mental notes: check if vmware somehow created the OS with some kind of dumb limit on inodes vs regular boxes.  That also shouldn't be possible I think.

**Comment by EliAndrewC** [comment]
Hmm, I'd have expected CherryPy to free the session file handlers after use, though it might be holding onto them for performance reasons, assuming that anyone with enough sessions to run out of file descriptors would be configuring CherryPy to store sessions in postgres anyway.

Even if this isn't the culprit we should probably have CherryPy store sessions in the database instead of on the filesystem at this point, and we should probably make sure that we don't create new sessions for API calls unless there's some reason we actually end up needing that.  (I'm guessing it's generating a pointless CSRF token and storing that in the session or something.)

**Comment by EliAndrewC** [comment]
Closing as a duplicate of #1748
