### ISSUE TITLE
Game Over: New York season pass invites

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1533]
GO:NY is the next event included in the season pass. It'll be October 11th at The Grand Victory in Brooklyn, NY.

Please send season pass invites asap.

**Comment by binary1230** [comment]
future note:  at some near-future point, we'll be migrating magfest-specific operations/config issues like this out of github and into JIRA.  

sidenote: YES!!! WOOHOO

**Comment by binary1230** [comment]
see https://jira.magfest.net/browse/MAGDEV-2 (mag devs only can access this)

**Comment by EliAndrewC** [comment]
Done.  BTW, for future reference, all I had to do was edit ``/usr/local/uber/plugins/magprime/development.ini`` on the production server to add the following:

```
[[game_over_ny]]
name = "Game Over: New York"
day = "2015-10-11"
deadline = "2015-10-10"
location = "The Grand Victory in Brooklyn, NY"
url = "https://www.facebook.com/events/858574664239550/"
```

While I'm happy to continue being the person to do this, it's a lot simpler than people probably think to add a Season Pass event.  Though admittedly, since we don't yet have puppet-managed ``development.ini`` files, it has to be someone with SSH access to our production servers, which limits the pool of eligible people.

**Comment by EliAndrewC** [comment]
Incidentally, @nickthenewbie1 had asked about whether we had more or less Season Supporter registrations this year compared to last year.  We currently have 26, whereas at this time last year we had 28.  Since we have more registrations now than we did at this time last year I'd say that not having the banner up top is hurting somewhat.
