### ISSUE TITLE
As a staffer, I want a better indication when there are no shifts available to sign up for

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1538]
A confused user sent us this screenshot which has no shifts available for signup:

![image](https://cloud.githubusercontent.com/assets/5413064/10310191/b1fb1ae0-6c0e-11e5-856a-254f2c7c1d06.png)

It would be great if we had an extra message here like "sorry, no shifts have yet been posted for any departments you are signed up with"

**Comment by EliAndrewC** [comment]
Wait, are people able to log into that page in the SuperMag site? That shouldn't be possible at the moment, since you shouldn't be able to log in until we've passed ``c.SHIFTS_CREATED``.  Someone should look into this.  I can do it after work if necessary.

**Comment by earl7399** [comment]
It's closed, at least when I try:
[image: Inline image 1]

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by binary1230** [comment]
no sorry this was from classic

**Comment by binary1230** [comment]
(sorry, was going through ancient emails)

**Comment by EliAndrewC** [comment]
Gotcha, good to know.  This is indeed a valid issue and worth improving, I just wanted to make sure there wasn't a much more urgent issue with our production server :)

**Comment by binary1230** [comment]
nope nope all good, not urgent right now : )

**Comment by bds002** [comment]
Ithink @cschmittiey was going to look at this.

One of the things I would like to add here is some verbage that to the effect says:
"You are currently  assigned (Insert departments), they currently have no open shifts listed, please contact them at: (Departmental Email address) for more information.  You can also contact stops@magfest.org for further details as well,

To do this, we would need to have a Import of C.assigned_departments and Department Email address.

**Comment by EliAndrewC** [comment]
Aaron asked me on Slack how to display a person's assigned departments and how to display that department's email address.

I'll answer the second part first because it's a simple answer: you can't display the email address of the department because not every department even has an email address, and we don't track that information in any kind of systematic way.  Alas!

That probably makes the proposed solution unworkable in the short term.  In the longer term we could start associating email addresses with departments, which would make this kind of thing possible.

If we still wanted to pass the volunteer's departments from our Python backend into the webpage, we'd first need to add it to the data being rendered by the template at
https://github.com/magfest/ubersystem/blob/master/uber/site_sections/signups.py#L72
by changing
```python
return {
    'jobs': session.jobs_for_signups(),
    'name': session.logged_in_volunteer().full_name
}
```
to something like
```python
return {
    'jobs': session.jobs_for_signups(),
    'name': session.logged_in_volunteer().full_name,
    'depts': ' / '.join(session.logged_in_volunteer().assigned_dept_labels)
}
```
Then we can refer to it in the template file.

At this point we have to decide whether we'd like to include it in our Angular app or not.  In theory we could change the ``<body>`` of our template from this

```html
<body ng-app="signups">
    <div ng-controller="MainController">
        <div ng-view></div>
    </div>
</body>
```

to something like this:

```html
{% if jobs %}
    <body ng-app="signups">
        <div ng-controller="MainController">
            <div ng-view></div>
        </div>
    </body>
{% else %}
<body>
    Sorry, there are no jobs available in any your departments ({{ depts }}).
    Contact {{ c.STAFF_EMAIL }} with any questions.
    Or whatever text is supposed to go here.
</body>
{% endif %}
```

Alternatively, we could insert the department info into the app but putting it on ``$rootScope``, e.g. saying ``$rootScope.assigned_depts = '{{ depts }}';`` at
https://github.com/magfest/ubersystem/blob/master/uber/templates/signups/shifts.html#L13

Then you can reference ``{{ assigned_depts }}`` in the Angular templates such as
https://github.com/magfest/ubersystem/blob/master/uber/static/angular-apps/signups/possible.html

**Comment by bds002** [comment]
I think short term (for M2016) we leave at a simple version and simply tell them to contact Staff Operations at Stops@magfest.org for more info. This is a nice refinement, but I also don't want us to get bogged down in extra details  when short and simply will work 30 days before event.
