### ISSUE TITLE
Should warn of minimum increment (5) for additional group badges

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1541]
I couldn't find anywhere on the live page for buying group badges where the purchaser is warned that the minimum increment for adding badges later is >1

**Comment by EliAndrewC** [comment]
There's a dropdown where the lowest value is 5 (or whatever is configured), but you're right that there isn't specific verbiage explaining that they have to purchase at least N badges.

**Comment by earl7399** [comment]
Right, that's when they come back to buy two more. We should warn them during the initial purchase.

**Comment by kitsuta** [comment]
Just to clarify, you mean the pre-reg page and not the group management page, right?

**Comment by earl7399** [comment]
Correct - we don't warn during the initial purchase, so pre-reg

**Comment by RobRuana** [comment]
Looks like this was fixed by https://github.com/magfest/ubersystem/commit/ae51386ad09dfbd44824ce84c8f02cff497a55e5?

I think that commit may have been tagged with a closely related, but ultimately different issue (#1989).

![screen shot 2017-06-13 at 11 58 33 pm](https://user-images.githubusercontent.com/2592431/27114817-49147078-5094-11e7-814f-d55fe98670b8.png)

**Comment by kitsuta** [comment]
Whoooops, yeah.
