### ISSUE TITLE
[2016] Send minor consent forms.

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1556]
A generic minor consent form has been created. Please send it out to all minors in the system, and make sure all future registered minors automatically receive it.

http://magfest.org/MAGFestMinorConsentForm.pdf

**Comment by kitsuta** [comment]
PS: This shoulda gone in JIRA.

**Comment by nickthenewbie1** [comment]
PS I DON'T KNOW ANYTHING ANYMORE THE WORLD IS MOVING TOO FAST FOR ME

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by earl7399** [comment]
It's official. Nick and I feel the same way about something. Armageddon is
here!

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by bds002** [comment]
Do we want to through the Code of Conduct short blurb or link in that document?

**Comment by nickthenewbie1** [comment]
Which short blurb are you talking about?

--
Nicholas Marinelli
Chief Operating Officer
MAGFest
http://magfest.org

**Comment by kitsuta** [comment]
The CoC link should already be sent to people and/or shown on the pre-reg page.

**Comment by bds002** [comment]
The thing I was thinking about is actually The short version of the Harassment policy, so that may not apply.  I still think we should link or mention the MAGFest CoC in this form as not all parents are going to see the Pre-reg page if a minor registers themselves.  

Something like adding to the 3rd I agree section: 
"I agree also to accept full responsibility for the actions and behaviors of above-named minor at MAGFest." I understand that above named-minor has also agreed to the MAGFest CoC as presented during the registration process and found here: http://magfest.org/codeofconduct.

**Comment by EliAndrewC** [comment]
This was handled earlier in the week.
