### ISSUE TITLE
Email all volunteers before MAGFest instead of only those with shifts

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#156]
The schedule has other information, such as food information.  So we should email everyone instead of only those with shifts, just to make things easier.

---------------------------------------
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/161
- Originally Reported By: [ ](http://bitbucket.org/EliAndrewC)
- Originally Created At: 2014-01-07T01:22:12.382

**Comment by kitsuta** [comment]
This issue refers to an email that I can't actually find in the system. When do we email volunteers with their schedules?

**Comment by EliAndrewC** [comment]
#569 covers actually mailing out the shifts.  Previously we would only email them something saying that they should log in and print out their shift schedule.

**Comment by kitsuta** [comment]
The volunteer food info email should go to all volunteers - is there anything else we need to do to address this, once it's enabled?

**Comment by EliAndrewC** [comment]
I don't think so; at a glance it looks like the config is good, though I haven't reviewed the text of the email.  I vaguely recall that @kitsuta already fix that though.

**Comment by kitsuta** [comment]
Yup, it should be good.

I've re-enabled the email in magprime_emails' init file. I stuck on `approval=True` so we don't have to worry about it in the future - we can leave it enabled in code and have the staff suite review the writing before it goes live.

Since the gist of this issue was "make sure all volunteers get food info" I'm closing it.
