### ISSUE TITLE
bug in badge_shift code

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1585]
I currently have a badge# of -1 :)

Looking at the history:
![image](https://cloud.githubusercontent.com/assets/5413064/11227821/7eeaf6fc-8d56-11e5-93fc-4fc925c40fe9.png)

@bds002  said that @EliAndrewC already knows about it, I did a quick search and didn't find anything, so, making a bug before I forget about it.

Pretty weird stuff, we do have some unit test coverage on this function but maybe not enough to cover this case?  Might be a good puzzle for the new code team.  Eli if you have insights, lemme know.

**Comment by EliAndrewC** [comment]
As I've said before, the badge shifting code is simultaneously the most unit tested and also historically the buggiest piece of code in the entire codebase.  Those two things are related; it's got so many edge cases and is genuinely very complicated, which is why we've written so many tests.

I have no idea what the specific bug is though.  My guess would be that it has to do with badge statuses, since that's the latest change that we've made to our system that might affect badge shifting, but that's just a shot in the dark.

**Comment by kitsuta** [comment]
I don't... _think_ badge statuses interact with badge shifting at all. Which in itself is a bit odd, since it means that invalid badges would take up 'space' in a badge range.
