### ISSUE TITLE
don't print non-complete or non-new badge statuses for staff/supporter badges?

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1648]
Should we exclude any staff/supporter badges being printed with statuses that aren't c.NEW_STATUS / c.COMPLETED_STATUS?

@kitsuta need some expert advice on this one.

maybe we want to create a method that answers "is this a real badge we expect to exist" that checks that stuff.

**Comment by kitsuta** [comment]
Yes, New/Complete are the only badges considered (potentially) check-inable. It may or may not already filter out other statuses - I know I added some checks to some generic utility functions. Would have to look into it more and see.

**Comment by EliAndrewC** [comment]
With that being said, Deferred badges probably should be printed, since in theory a Deferred badge might be checked in.  For example, a badge might be marked as Deferred if the attendee name matches a name on our watch list, but we might find at the event that they're just a different person with the same name (as has been known to happen).

Invalid badges should probably NOT be printed, since Invalid basically means "deleted".

**Comment by bds002** [comment]
I know of 2 different uses of Deferred badges -
- 1 we are using that for staff not label to attend and being deferred to M2017.  
- 2nd I think Arcades is using it to verify their Badge for Cab people before the badge is kciked to New/Completed.
