### ISSUE TITLE
The volunteer login page can return an Invalid badge

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1676]
If a staffer has an invalid badge and a valid badge, and the full name and zipcode are the same on each, the volunteer login page (https://prime.uber.magfest.org/uber/signups/index) may log them into the invalid badge. So when they log in, they immediately see the "Invalid Badge" page.

The volunteer log in should either ignore invalid badges or at least prioritize non-invalid badges.

**Comment by EliAndrewC** [comment]
@DataFighter: after you're finished with your other ticket, this would be a good next one to tackle.  When you're ready, I can walk you through what needs to be done - it's basically just modifying the ``session.lookup_attendee`` function which you already modified in the previous PR so that it excludes invalid badges from their search.

**Comment by EliAndrewC** [comment]
fixed in https://github.com/magfest/ubersystem/pull/2315
