### ISSUE TITLE
Recent At-Door Registrations will not enforce badge types

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1678]
On the "recent at-door registration" page (e.g. https://stage.uber.magfest.org/uber/registration/new), it is possible to enter badges of the wrong type when checking in users. So someone could pay for a one-day badge, but if their badge number is entered as 3263, the system will accept it and change the badge type to match.

**Comment by EliAndrewC** [comment]
Hmm, interesting.  From looking through the code, it looks like I deliberately coded it to do that, probably back in M9 when this the first version of this page/feature was originally implemented.  At that time I could totally see myself saying, "Eh, they entered it wrong, but they just paid in cash, so instead of having to go in and change the badge type, I'll just have it do the correct thing based on the badge number."

I'll charitably say that this made sense at the time, but I agree it's not a good behavior for us now, and should be changed.
