### ISSUE TITLE
Make Recent-at-door Registrations DataTables searchable

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1705]
Right now, you need to use Ctrl-F to search in the "Recent At-The-Door Registrations" page. It'd be a little nicer if volunteers could search using the DataTables instant search box.

**Comment by earl7399** [comment]
+1 on this suggestion. If I had a chance in hell of actually doing it, I'd work on that today to the exclusion of almost everything else.

**Comment by EliAndrewC** [comment]
I'm glad you said that @earl7399 - I probably would have just marked this with the ``newcomer`` tag and left it as a low priority feature otherwise.  But since it's clearly something that makes a much bigger difference than I thought[*], I've assigned this to myself and will jump on it in a few minutes.

[*] It's a bittersweet feeling that I'm now separated enough from the registration department that I no longer even know which features are most important.  In the old days, I was writing the software for myself, and since I worked every part of regdesk I knew exactly what was easy/hard/needed.  Every year I inch closer to being the pointy haired boss :P

**Comment by ksonney** [comment]
@EliAndrewC There is a fix for that - spend some time working for each department. I'm sure @kitsuta would appreciate the help. :) I advocate very strongly that developers/engineers spend a day/shift/something with each "class" of user to better understand use cases.

**Comment by EliAndrewC** [comment]
FWIW, I do spend time checking people in every year on the Tuesday/Wednesday before MAGFest to make sure the system is working and that everything seems sane.  I also do this at other events that use this system such as MAGStock.  In both cases I also watch other people use the software to check people in, since it's super-important that newbies using the system will find it intuitive.

In this case my blind spot is that I don't work at-the-door registration, which is definitely a class of user I've largely lost touch with.  Unfortunately, each "class" of user for MAGFest is probably like 10 different departments (reg, at-the-door reg, merch, stops, mivs, chefs, tabletop, lan, chefs, etc), which at the moment is not something I can feasibly do, because I'm still too tied down to Stops.  With that being said, I'm hopeful that eventually Stops will be in such amazing shape that I can just work like 1 shift there to make sure everything works, and then I'll have time to do as you say - floating around to different departments and doing a little of everything to make sure that everything is sane/good and not having to rely on users as much to make suggestions and report deficiencies.

This might be feasible as early as next year; Brent has been doing a fantastic job recruiting Stops managers, so we're probably not too far away from me being able to step away from Stops in the same way that I've stepped away from registration.  Regardless, "my goal at MAGFest is to have nothing to do because everything can run without me" is the mantra for everyone in a leadership position, and we're getting closer.
