### ISSUE TITLE
Move sessions to database

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1748]
CherryPy allows us to store sessions in the database, and we should do this instead of doing it in flatfiles.

**Comment by binary1230** [comment]
some more info for those tuning in:

each user's session data (i.e. the thing that a user's cookie gets them access to) is currently being stored as an individual flat file on the disk.

this works fine as-is but, if we ever move to having multiple backends it won't work since the session data will need to be stored in a shared location between all backends
