### ISSUE TITLE
Track group payment composition better

### ISSUE THREAD

**Issue by zebranky** [magfest/ubersystem#1749]
I can't find a way to see how much a single group member "contributed" to a group's payment. This is an issue, e.g, when someone accidentally entered an under-7 DOB and presumably paid that rate, but it's impossible to determine how much they should pay to square up.

**Comment by kitsuta** [comment]
Group payments work the way they because typically, the entire group's payment is put onto one card, so multiple people don't actually contribute to the group's payment.

That being said, the refactor for group payments actually addresses this (or at least, what I think this is getting at), because group payment is now based on the group's attendees' "base badge price"s. So you should now be able to look in the attendee's details page to see how much they 'owe'.
