### ISSUE TITLE
Add option to change admin account password

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#1784]
It's inconvenient to have to delete and recreate a user's account in order to change their password. Having a way for admins to set a user's password would be great.

**Comment by EliAndrewC** [comment]
I removed the "force password change at first login" portion of this issue and moved that to a separate issue at #1785

**Comment by kitsuta** [comment]
I closed this because I thought that the use-case was no longer applicable, but @ShevaDas has informed me that plenty of volunteers are incapable of remembering their passwords.

We'll want a little more discussion on how this is done, though -- specifically, whether or not we trust people with accounts access to be able to change anyone's password arbitrarily. At the very least, this kind of action needs to be logged and should ideally also require a confirmation of the existing admin's password (which prevents the thing _I_ worry most about, "someone left themselves logged in and they have a billion permissions, now any schmuck can take two seconds to muck things up").
