### ISSUE TITLE
prereg form renders slowly server side - excessive TTFB / time to first byte

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1956]
purely on the server side, on my local environment (which might have slower disk access), it seems to load a lot longer these days, around 15sec.  on real servers feels a bit faster but still at least a few seconds for that page to come up.  this is probably worth a quick run in a profiler to make sure this page isn't eating up too much CPU spinning on something easily optimizable.

```
uber.site_sections.preregistration.form loaded in 14.946598 seconds
uber.site_sections.preregistration.form loaded in 15.32359 seconds
uber.site_sections.preregistration.form loaded in 16.511649 seconds
```

not necessarily a launch blocker but... could spell trouble if this is a CPU bottleneck and we have a large rush.

**Comment by thaeli** [comment]
Profiling from my browser on staging3, I see two things that are majorly slowing down page load.

The prereg form itself takes about 3.7 seconds to render - this is dead air for the user and is where server side profiling might help.

Then, combined.js is 3MB. This will be the bulk of load time on a slow connection, especially since it loads synchronously and blocks page load / usability. Fixing this is a longer term project to completely refactor how we do client side JS. (Yes, caching should help, but seeing as how this is a page that we expect cold-cache users on 3G phone connections to use, making the JS lighter weight would really help.)

**Comment by binary1230** [comment]
so yea i do agree that there's probably a ton of work to do on the client side as well to make things speedier, but, I'm specifically referring to JUST the server side rendering of the initial page HTML, which is timed at 16 seconds before any data is sent to the client.  you're right that the real page load time is that amount plus an additional ~4seconds for the JS and rendering, but, I'm specifically ignoring all the client stuff and just measuring how long the server takes to send the HTML out.  so I think this is something on the prereg form, and we would need to profile the python execution and template rendering to find out what's up

**Comment by thaeli** [comment]
Ok cool. I changed the title to make it clearer this is about server side rendering / TTFB issues not overall prereg form pageload performance.

**Comment by binary1230** [comment]
cool, and, we could probably make a separate issue about the client-side rendering too

**Comment by binary1230** [comment]
fixed a really egregious version

**Comment by binary1230** [comment]
my understatement for the year "not necessarily a launch blocker" :)

I think we can call this fixed now.  load times are .2s to .4s now
