### ISSUE TITLE
MAGLabs: Volunteer Perks Change

### ISSUE THREAD

**Issue by JennyTruss** [magfest/ubersystem#2002]
Change "3 hot meals" to "hot meals". We are dropping lunch to free up time for dinner prep and to enjoy the fest.

**Comment by earl7399** [comment]
Where does this text appear? I'm having trouble locating it in the repos

**Comment by JennyTruss** [comment]
https://labs.uber.magfest.org/uber/static_views/stafferComps.html

**Comment by bds002** [comment]
The Research Team @jcooter @migetman9  needs sign off of this change at this stage of MAGLabs. 
We have been advertising 3 meals since registration opened and I believe it's part of the Band contract information as well.

@earl7399 The actual from resides at:
https://github.com/magfest/hotel/tree/master/hotel/templates/static_views

**Comment by JennyTruss** [comment]
Well, something to keep in mind is that I was approached by Squid about possibly removing a meal to allow more prep time prior to being selected as DH for MAGLabs. It was also recommended by Nick and Paul has always said we have full discretion on that matter. We also weren't selected to run the Suite until after I had a major life event happen, only 2 weeks before the first deadlines, so making sure all of that was in order wasn't on my priority list until I had a chance to look it over. If you want to count overnight as one of the hot meals, then yes, it is 3 (breakfast, dinner, overnight). Lunch just isn't a full lunch, just mostly snacks.

**Comment by RobRuana** [comment]
I'm pretty sure this is no longer relevant...
