### ISSUE TITLE
Send attendees barcodes to speed up check-in

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2107]
Many other ticketing systems allow attendees to print out a 2D barcode to enable faster check-in. We want to do the same. Our system would:

- [x] Generate an encrypted 2D barcode that maps to the attendee's unique UUID, plus encodes a unique event identifier.
- [x] Automatically send an email to attendees that are Completed status with their check-in barcode.
- [x] Make sure to warn attendees that their photo ID _is still required_ and the barcode simply makes check-in faster.
- [ ] Automatically pop-up a check-in dialogue for an attendee if their barcode is scanned on any /registration/ page.
- [ ] (Optional) Also allow volunteers to scan the 1D barcode on the badge to assign that badge number to the attendee while on their check-in page.
- [x] (Optional) Check the event identifier and return a unique error if it is incorrect.

Note: Yes, the barcode must be encrypted. Attendees' UUID is sensitive data.

**Comment by binary1230** [comment]
My quick notes on this:
* For the email containing the barcode, if possible we should figure out if we can send the barcode image as an attachment, and not as a hotlinked image.  i.e. ideally the email should not contain anything that references the server name directly like ```<img src='http://super2017.uber.magfest.org/whatever/barcode?id=asdfasdfasdf'>```, instead it should be embedded into the email.  That way if our server if offline, onsite, or just unavailable long after the event, if someone is trying to print their barcode, it won't mess with anything.  I don't know exactly how to do this or if its possible. I think it should be?
* It looks like a legitimate priority to get us scanning the badge barcode this year instead of typing in the badge number.  The main 2 reasons are badge number accuracy, and speeding up checkin by not having to make the reg volunteers type in a badge# by hand.  We definitely encountered the situation at labs when doing LAN checkins where someone's badge# was typed into their record incorrectly, and when LAN tried to look up their info via the badge barcode, the barcode mapped to a badge# which was not yet associated with an attendee.   i.e.  situation similar to this: attendee had, physically, badge 300 on their person.  but in ubersystem, that attendee's record was (incorrectly typed) as badge 30.  when barcode scanner attempted to look up the name of the attendee with badge 300, it came back as no one.

**Comment by binary1230** [comment]
actually hey I just looked up how to do email attachments and I don't think our current AmazonSES() class would support it without a bunch of rework or replacing it with something else, so I guess, consider the image attachment idea optional for first-pass implementation on this.

The other thing we could do is create a standalone app which lives permanently on the cloud whose only job is to generate barcode images from ID's.   so you could link to it via email something like this:  barcode.uber.magfest.org/generate?id=whatever

Then it's independent from the rest of ubersystem and doesn't require our onsite server to serve up a bunch of images to the internet
