### ISSUE TITLE
As a MAGFest staffer, I want to be able to continue sending emails from Uber at-con.

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#2117]
Emails don't send when Uber is switched to at-con mode. This is a problem for reg because attendees get nervous when they buy a badge and don't receive a confirmation email. (It also bit us at MAGLabs when we tried to send out the pre-event info email that Thursday and didn't realize it didn't send until Friday. Whoops.)

Can we continue to send emails when Uber is in at-con mode?

**Comment by ShevaDas** [comment]
alternate user stories: "As an attendee, I want to keep receiving emails from MAGFest during the event."; "As an Ubersystem, I want to retain my ability to send emails at the event."; "As an email, I want to fly free and deliver my missive to the correct recipient, regardless of our position in spacetime."

**Comment by earl7399** [comment]
IIRC, part of the issue is that at least *some* of the e-mails are worded
in such a way that they refer to a future event, and the concern is that
recipients might end up more confused.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by binary1230** [comment]
I was thinking about this one for this year (Jan 2017), especially because of https://github.com/magfest/ubersystem/pull/2196/

I was thinking we could do this pretty simply by adding a new param to send_email() which explicitly allows emails to be sent in at-the-con mode.

Then, we can:
1) modify the AutomatedEmail class to run at-event and also pass in this param to send_email()
2) modify one-off send_emails(), like in the accounts admin code, to be able to pass in this param to send_email()

This would allow us to turn on automated and one-off emails on a per-email basis, instead of all or nothing.  We could focus on receipts and Admin Account stuff first, add things as needed.

**Comment by kitsuta** [comment]
We fixed this for MAG 2017. Woo!
