### ISSUE TITLE
Creating a badge for a babe in arms causes a negative base price.

### ISSUE THREAD

**Issue by ghost** [magfest/ubersystem#2207]
![capture](https://cloud.githubusercontent.com/assets/17105439/21213066/123fb8e0-c260-11e6-83bc-2f128b390023.png)

[sensitive info removed by Dom]

**Comment by binary1230** [comment]
can you describe the steps to re-create this issue just so it's documented here?

like 1) create badge with birthdate of X, view page, expected result: $0 charge actual result: -$919.00 price

**Comment by iollan** [comment]
Look at https://magfest.slack.com/archives/reg-heads/p1481580428000710 and https://magfest.slack.com/archives/reg-heads/p1481687292000757 and https://super2017.uber.magfest.org/uber/registration/form?id=3c908ae9-62d4-4bff-bb5c-a5cd55291e2c. You should have access to all of these.

**Comment by binary1230** [comment]
@iollan 2 things: 

A) I removed the links to the badge in the comments here because this is a public comment and that link would have given anonymous viewers access to modify or transfer that badge.

B) The issues tracked here in github need to have full context in here in order for coders to work on them (coders that might not necessarily be me or vicki, or have access to the private reg-heads channel in slack, or even have a magfest slack account).

When filing bug reports, we need information about what the bug is, how to trigger it (if it's repeatable), and what the expected vs actual result is.  This is important because we are constantly managing a large flow of bug reports, so people organizing this might not know or be familiar with the details, and these details help prioritize the bug to know if we need to drop everything and fix this right away, or if it's something that can wait til after the event.  

Then, after the event, everyone (including you) might look back in 2 years at this bug and not be able to understand what the original issue was, or if it still needs to be fixed, or even how to trigger the bug to know if it's been fixed already.

For every bug we'd like to see a report like the following:
1) overall description of the bug: "it's possible to get a negative amount paid for child badges"
2) steps on how to reproduce this bug:  i.e. something like 
  i) visit prereg page 
  ii) select child badge, enter a birthdate of X, hit save   
  iii) visit admin page and look at this badge

3) tell us the Expected result vs the Actual result like this:
EXPECTED: badge price listed at $0
ACTUAL: badge price is negative

It's crucial these details are attached to every bug report and that each bug report has standalone context that doesn't assume the coder knows how to trigger the bug, or has access to slack or uber credentials to view it.

If you don't know the repro steps, it's OK to just note that there's bad data somewhere and you're not sure how it got there.  The more info in the bug report, the easier it'll be to track down.

---

**Comment by binary1230** [comment]
Also, the screenshot is really nice that's great to have

**Comment by binary1230** [comment]
Also, for this particular bug, @kitsuta is already way way on top of it with a fix at https://github.com/magfest/ubersystem/pull/2238 so we don't need further documentation here.

And also, reading the context in slack, to be fair to @iollan: @kitsuta did mention in the chat that just a screenshot would be fine because she's likely the one to fix this bug anyway and that's cool.  Just, when @migetman9 and I were looking at it we were like 'what does.... babe in arms mean, what is this bug?'

So, not trying to come down on anyone, just, if you have the time or info, provide the context if it's available. ANYWAY none of it matters here because the pull request is ready.

**Comment by iollan** [comment]
Okay honestly, I did what I was told. Frankly code is one of those things I don't want to get involved in so I'll just report in devops and ya'll can make the tickets. I do enough as it is and really don't have the time or desire to add something else to my plate. And next time you want to scold me do it in a private channel. I'll be deleting my github account after this,
