### ISSUE TITLE
As a Staff Ops person, I need a search funtion on the sent email pages

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2218]
When Uber sends out the Hotel room assignments emails, those do not get copied over to the attendee history record. - Part if this is because it would have to hit all records involved - 3-6 users usually.

When there are changes to be made, it becomes increasingly difficult to search through the log file at: https://super2017.uber.magfest.org/uber/emails/index? in order to find the correct date/ time and email information.

Looking to get a Search box added to the /index page that would search for outgoing email addresses.
The page in reference is currently 267 sections long.

**Comment by kitsuta** [comment]
Ooh, yes, this would be nice.

For many of our tables we use a jQuery plugin called DataTables and we just load all the records on a single page. However, since we will by definition have at least as many sent emails as attendees, we can't use this as a cheap shortcut because that is a LOT of client-side records to load at once. Instead, we'll want to copy and adapt the server-side search functions used here: https://github.com/magfest/ubersystem/blob/master/uber/site_sections/registration.py#L45

Note that this bit of code points to a function in `models.py` that only searches Attendees. So, uh, don't use that. It should be a pretty simple filter statement, anyway (unlike attendee search, which searches multiple parts of the record based on the format of the search terms). https://github.com/magfest/ubersystem/blob/master/uber/models.py#L715.
