### ISSUE TITLE
Review whether kiosk page displays supporter swag options.

### ISSUE THREAD

**Issue by BlueHat-GURU** [magfest/ubersystem#2224]
If it is displayed, please hide it.

**Comment by kitsuta** [comment]
It does display the kick-in levels.

We can fix this relatively painlessly by altering what we do with PREREG_DONATION_OPTS in config.py. Right now it just returns anything below the Supporter kick-in level -- we can just tell it to return nothing if we're in at_the_con mode. We may event want to do this in the magfest plugin so that other events can sell upgrades at-door (this is pretty common in my experience, since most events' upgrades do not come with as many... materials as ours do).

**Comment by thaeli** [comment]
To add how all the Oni events do it, which is a pretty common use case for
many other events as well: kickin levels are either "at the door" or "pre
reg only" - the latter cut off when badges_ordered happens. Though it
should probably be a separate cutoff.

Note, the other big feature they need that we don't have yet (again a very
common use case, and one I think Mag may actually need at some point as
well) is quantity limits on kickin levels and ability to buy
kickins/add-ons alacarte instead of only as kickin levels. I think this is
a "let's hack it IN THE MAGFEST PLUGIN for now" and will be long term
addressed by that merch rewrite I need to do.

**Comment by kitsuta** [comment]
Yes, also this could potentially be fixed by making the 'shirt deadline' actually do a thing, as detailed in https://github.com/magfest/ubersystem/issues/2210 (right now it's a 'text' config option, but we could/probably should make it actually turn off shirt_level and above kick-ins).
