### ISSUE TITLE
attendees are unable to complete prereg for standalone child badges

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2230]
You can't currently create a child badge on the prereg form, ubersystem will ask for a credit card and then be unable to continue:

repro steps:
1) visit prereg page, create a child badge with birthdate less than 6 years old 9 (i.e. born  in, say, 2014)
2) notice that you have a $0 badge in your cart
3) notice that uber is asking for payment of $0 and asks you to enter a credit card
4) enter payment

EXPECTED RESULT: either you are never asked for payment in the first place, or your $0 payment goes through and you are successfully registered

ACTUAL RESULT:  you get a message that says 'Your preregistration has already been paid for, so your credit card has not been charged'

![image](https://cloud.githubusercontent.com/assets/5413064/21510164/37a377ea-cc5e-11e6-8692-732565f20f58.png)

-------------------

technical notes:

we should not be asking for a credit card in the first place, instead just calling something that marks the attendee as paid or doesn't need to pay or similar in the DB

**Comment by kitsuta** [comment]
I'm going to argue very weakly that attendees should really be registering children with an accompanying adult badge, which would of course result in a payment.

I'm sure there's plenty of legit situations where people would need to register only kids, but possibly a better solution is to add an explicit error (e.g., 'you can't just register minors without an adult') and then allow someone to add a kid via their confirmation page. This will probably result in a worse user experience overall but will also definitely communicate the need to actually have an accompanying adult badge, so I'm pretty ambivalent about our approach.

Fixing the bug is probably easier, but let's just keep the alternative in mind for if we find a lot of attendees picking up child badges without an adult badge.

**Comment by thaeli** [comment]
We should get a Dorsai opinion on this. I know they like being able to look
up parents of a child badge in lost-kid situations and emergency contact
doesn't always get filled out helpfully..

**Comment by kitsuta** [comment]
By 'add a kid' I do just mean adding a new registration via a different workflow.

**Comment by BlueHat-GURU** [comment]
Admins can add currently, so this is not hair on fire.

**Comment by BlueHat-GURU** [comment]
2 cents: I like the idea of "add child badge[s]" being an option after an adult has registered, and not otherwise. Or a modification for an already registered adult. That said, my coding skills are at the level of "just enough to be dangerous" so I'm not sure how much trouble implementing that option would be.

**Comment by binary1230** [comment]
updated info from phone call with @kitsuta and input from reg: this isn't as high a priority as I was originally crying wolf on (just because it's actually an edge case for people to buy JUST a child badge, usually they buy it with an attendee badge and that's cool).

dare had an emergency fix for it in #2231 but looks like we can take our time to solve this in a solid way

**Comment by kitsuta** [comment]
Fixed by #2238.
