### ISSUE TITLE
- Verify Uber is calculating Shift hours correctly.

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#2260]
We have a staffer - Pawlowski
Who is signed up for "42.875 weighted hours" via their Volunteer Checklist/Login.
However the email with subject: "MAGFest hotel room requirements" only records them with 28.125 hours.
Those two hour numbers should match and I don't see where the discrepancy is coming from.

**Comment by bds002** [comment]
![capture](https://cloud.githubusercontent.com/assets/8822346/21576607/59b8d8cc-cf04-11e6-8e80-5768f12cd658.PNG)
Ok there is definitely something wrong with the Shift hours calculations.
That attached is from Escape Room for MAGFest 2017
https://super2017.uber.magfest.org/uber/jobs/staffers?location=126051544

The first 4 people listed are only in Escape room and Hours Here are different that the Hours total. 
If these folks are just in 1 department, these hours should be the same.
@BlueHat-GURU I am requesting this be bumped up in the code stream - still secondary to making sure Onsite Reg is working, but Since Hotel room 30 hour verification is dependant on the calculations it starts to become a mess rather quickly.

**Comment by kitsuta** [comment]
That is a confusing discrepancy on this page. However, as far as that page is concerned, it's just a UX problem. The thing that `hours here` doesn't count but `weighted hours` does is non-shift hours. The four people in that department with the discrepancy all have 36 non-shift hours. So the data itself is... fine.

The email being wrong is a separate issue. And in this case, I _believe_ that it is because of this:
`Shift	deleted	11:23 on December 30 2016	Tronster Hartley	id=bcd9e842-5c57-4a27-959c-d82c5f2085a2` (note: the ID here is a job ID, not an attendee ID)

The staffer received the email three minutes after this action. Unfortunately it looks like an attendee's history page doesn't actually log that attendee signing up for more hours, but that must be the cause of the discrepancy -- the email text uses the exact same variable that generates the "42.875 weighted hours" that you see now.
