### ISSUE TITLE
Make check-in barcodes unencrypted but unrelated to attendee.id

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2343]
For MAGFest 2017, we took the attendee's UUID and encrypted it to make the check-in barcode. However, encryption is kind of a pain to do, it's breakable, and the easier solution is to just add a new UUID to the attendee specifically for searching purposes. We should add this UUID to the Attendee class and change the check-in barcode to be just that so we can skip encryption.

**Comment by thaeli** [comment]
We are, uh.. accumulating a lot of attendee unique-keys. That's ok! But I think it's time to think about how we store and manage those.

* GUID - the real database-level "primary key", which is currently also trusted for various things
* Badge number - super public and super simple identifier
* Badge non-human-readable identifier - Something in a barcode symbology only, or TID of an RFID chip, or possibly both because let's be honest, this is us.
* LAN barcode ID - whatever LAN uses now, hopefully can be replaced with the BNHRI.
* Registration confirmation identifier - The one that gets sent out in registration emails. It's basically a record locator too, just for use in different circumstances.

I probably missed some. But this basically is, "True Name" and "loads of aliases". Also, someone needs to come up with a better name than BNHRI. Because just in that list above, we have GUID, badge number, and three different BNHRI's. There's got to be a better way to approach this.

**Comment by EliAndrewC** [comment]
FWIW, the "registration confirmation identifier" is the same as the attendee id.

In the long run we should only need 3 identifiers if you count the badge number:
- the badge number, once they're checked in and have a badge number
- the attendee id, which is semi-sensitive in that having it allows you to do things with the badge
- the attendee public d suitable for a barcode which doesn't give you that ability

That seems sensible.  I'm indifferent about whether LAN uses their own thing or re-uses one of those existing numbers, since it's a separate codebase.

**Comment by thaeli** [comment]
This issue was to add an additional identifier, so that the attendee ID and registration confirmation identifier would not be the same thing. Are you saying that you disagree that this is needed?

**Comment by kitsuta** [comment]
Nah, I think Eli just got turned around on what you meant by 'registration confirmation identifier' -- it only goes out in the QR code email, but the GUID is used in all other registration emails.

The only ones he doesn't list that were in your list are the "Badge non-human-readable identifier" (super necessary if we go RFID, possibly necessary in other cases) and the LAN barcode ID which he did mention as being separate.

**Comment by kitsuta** [comment]
About LAN's barcode, I am vaguely hoping we can get them to use something that we print on the badges outright on the argument of "stickers peel off and that's probably bad."

That being said, apparently our barcodes could get scratched off pretty severely this year because they're printed as raised text and not stamped in. Oops!

**Comment by earl7399** [comment]
....if we have a unique ID (the QR code) intended for use in looking up a
registration, does it make more sense to send *that* out in the e-mails?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
No, because the entire point of the search key is that it's a uuid that we
can freely pass out because it requires admin access to do anything useful.

**Comment by earl7399** [comment]
I guess I'm concerned about the registration record being so immediately
available.

Will the persistent DB protect it by requiring login from the non-admin?

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
The overall conversation of "should we require a login to access attendee records" is far, far out of the scope of this issue. For MAGFest, the answer will probably end up being that you can optionally create a login for your record, but if you don't, we'll do the thing we've been doing for over ten years.

**Comment by earl7399** [comment]
I understand, but still has a sad.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by thaeli** [comment]
Getting back to the core of this issue: I have an alternate proposal.

We use the existing GUID as the non-human-friendly identifier *everywhere*. We then generate a number of authentication keys that are either signed or stored (I suspect signed will be less mess in the long run) and to take an action using a GUID you need to also provide an auth key with appropriate access. (Think of ` AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` - the former is public and useless to do anything privileged without the latter.)

This makes it simple to have a "register with this GUID" auth code, a "has been checked in" auth code, a "edit my badge details because i don't have an account" auth code, etc. It also means that you can expire/revoke an auth code without having to affect all other uses of the GUID elsewhere.

We will still need to support a list of alternate identifiers - badge number, RFID TID, etc - but this might help hold down the potential future explosion of identifier columns and the other alternate identifiers could go in a single `list_of_alternate_identifiers` column or something.

**Comment by kitsuta** [comment]
(note: a lot of discussion about this is in the related PR)
