### ISSUE TITLE
As an attendee, I don't want periods removed from my email address repeatedly without explanation

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2392]
If you register with a gmail.com domain, the system currently strips periods from your email address. While you'll still receive emails, this can be confusing when you try to correct your email on your confirmation page only to have it change back without any explanation. If possible, we should avoid altering attendee-facing data when we don't need to.

**Comment by EliAndrewC** [comment]
It would indeed be great to have a better system than this.  With that being said, this feature was implemented because the system had a lot of missed matches on people who don't enter their email consistently in different sub-systems, e.g. someone in MIVS entering a different email address than when they preregistered.  More importantly (and this was the reason for this feature), we had people telling us they couldn't log in as a volunteer when ti turned out they were just entering their email inconsistently.  (We now store the normalized version and then normalize what they enter on the volunteer login form before checking it against the database.)

The best solution would probably be to do something like storing both the attendee's entered email address and their "normalized" email address, e.g. one which is all in lower case and which performs any other provider-specific options such as stripping periods from GMail addresses.  We could then run the ``normalize_email`` function on addresses before we check the database for them, and only compare them to the ``normalized_email`` column instead of the ``email`` column.  Or something along those lines.

**Comment by earl7399** [comment]
IMO the best choice is to store what the attendee types, and perform any
massaging (like removal of periods from gmail addresses) *only* during
whatever checking we do - i.e. on-the-fly, never storing the massaged
address.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by EliAndrewC** [comment]
> IMO the best choice is to store what the attendee types, and perform any massaging (like removal of periods from gmail addresses) *only* during whatever checking we do - i.e. on-the-fly, never storing the massaged address.

That would work, but might not be performant.  Like in the case of logging in as a volunteer, we want to do a SELECT statement comparing the email they entered to every email in the database.  That means we need to do one of three things:

1) As in my suggestion above, store the normalized and raw email addresses in separate columns.
Pro: performs well.
Con: extra database column we need to keep in sync, which is icky.

2) Have a ``normalize_email`` Python function and run it against every email address in the database when someone logs in in order to do the comparison.
Pro: no extra column
Con: performs poorly

3) Implement a ``normalize_email`` stored function/procedure in our Postgres database, either instead of or in addition to our ``normalize_email`` Python function.
Pro: performs well AND doesn't need an extra database column
Con: now we're dealing with stored functions, which is a can of worms we haven't opened yet, plus we might have to keep the database and Python versions of the function in sync

Between the three above options I'm still inclines towards 1.  However, if the ``normalize_email`` function is simple enough, we could probably implement it in Python using SQLAlchemy and not even need it to be a stored function.  At that point we could implement option 3 with all of the upsides and none of the downsides.  That might be the eventual way forward.

**Comment by RobRuana** [comment]
Could probably do it with a property column, so the massaged version isn't stored, but we can still query against it.

**Comment by kitsuta** [comment]
That was my first thought as well. Any downsides to that?

**Comment by earl7399** [comment]
Property Column? Google-fu returns no useful results...

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by EliAndrewC** [comment]
SQLAlchemy lets you implement ``@hybrid_property`` properties which do one thing when run in your Python code and another thing when used in a query.  This lets you actually write Python code that translates into SQL code in the query, which is what I was referring to with my "we could probably implement it in Python using SQLAlchemy" comment, though obviously I was so vague as to leave that really unclear just what I was talking about.

I think that could be a good approach; assuming the ``@hybrid_property`` looked sane, it would probably be the best of all worlds.

**Comment by earl7399** [comment]
Thanks for the explanation!

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by RobRuana** [comment]
Yes, I was talking about SQLAlchemy's `column_property` detailed [here](http://docs.sqlalchemy.org/en/latest/orm/mapped_sql_expr.html#using-column-property). The `@hybrid_property` that Eli mentioned is also described on that same page.

The cool bit is we can instruct Postgres to create an index based on our `column_property`, so even though we aren't storing the massaged value in the database, we can still achieve fast lookups and joins based on the massaged value (technically the massaged value _is_ stored in the database – in the index – but it's automatically kept up-to-date by the database).

There would be some performance penalty during writes, because the index would be updated whenever an attendee's email changes. But that shouldn't be a problem, because attendee email probably doesn't receive a huge number of updates.

**Comment by kitsuta** [comment]
Just an additional note here: this is extra troublesome for folks who have admin accounts, because we DON'T normalize emails on the login screen. Someone trying to login with my.name@gmail.com will be told no account exists, because we think they're myname@gmail.com.

**Comment by jcooter** [comment]
We should not be doing normalization of any kind on the left hand side of an email address.  The email RFCs do not mandate case insensitivity, or routing for addresses based on non-alpha characters.

This means that MyName@example.com can be a completely different mailbox than myname@example.com for one provider, where another treats mailbox names as case insensitive.

**Comment by earl7399** [comment]
Agreed!

I routinely send to SPAM anything that comes to raearl@gmail.com - since
anyone I've given my address to has r.a.earl, so 99.9% of the time it is
just crap. We *really* should keep the address the user gives us.

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086
