### ISSUE TITLE
Change "Legal Name" to "Full Name" on Registration Confirmation

### ISSUE THREAD

**Issue by ShevaDas** [magfest/ubersystem#2437]
After registering for a badge Uber takes you to the Registration Confirmation page:

![image](https://cloud.githubusercontent.com/assets/3937986/25239536/1f16b656-25a5-11e7-8b3f-ca834a98e178.png)

Although the field says Legal Name, Full Name is used instead. Legal Name doesn't actually need to appear here IMO so maybe we can update the field title to say "Full Name" instead.

**Comment by RobRuana** [comment]
Good point by khyperia on Slack:

> khyperia [11:45 AM] 
Probably lots of instances of that - whoever takes that on should probably do a full search of the world "legal" over the code and hopefully make sure that everywhere it's used is proper. The opposite direction, the problem of using someone's usual name instead of their legal name, is more difficult to find, but hopefully lots of bug reporting should find most/all issues.

This issue should also include a full search for uses of the word "Legal"

**Comment by kitsuta** [comment]
https://github.com/MidwestFurryFandom/rams/commit/16b83d50815319366065893ebff9ae6dda459eea
