### ISSUE TITLE
As a placeholder badge recipient, I should be able to modify the legal name field.

### ISSUE THREAD

**Issue by jcooter** [magfest/ubersystem#2454]
Today, Rob created a placeholder badge for me for the labs instance, however he was unaware that I have a legal name that differs from the name I usually go by.

Knowing this information probably shouldn't be put on the user creating the badge, and during the registration process I should be able to change the value of the legal name field.

**Comment by kitsuta** [comment]
A worse permutation of this problem is the following:
1. Admin enters the exact same name on `legal_name` as `first_name last_name` because the placeholder form tells them to fill the field out and they don't know what else to do.
2. Our model_checks don't catch this because it's a placeholder badge.
3. The staffer goes to fill out their badge, presses Confirm.
4. Our model_checks tell them that they can't save the badge because their legal_name is the same as their first and last name.
5. They can't change the legal_name so they're stuck.

**Comment by kitsuta** [comment]
We've fixed the nastier permutation of this via https://github.com/magfest/ubersystem/pull/2459. The fix for the original comment is incoming.
