### ISSUE TITLE
As an attendee, I don't want to print out a barcode if the barcode scanners won't be available and working at registration

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2487]
There have been issues with the barcode scanners:
* Not every registration kiosk has barcode scanners 
* Not every barcode scanner works 100% of the time

Uber currently sends out a barcode email with instructions to print out the barcode for expedited checkin. It's frustrating for attendees who take the time to print out the barcode and then show up and they aren't able to use it.

We should take the following steps:
* Do not send out the barcode email
* Test the heck out of the barcode scanning code to make sure it works 100%

If we can get the scanners working 100% then do the following:
* Purchase enough barcode scanners for every reg kiosk
* Send out the barcode email a week or two before the event

**Comment by EliAndrewC** [comment]
Note: the specific config option is ``use_checkin_barcode``

**Comment by kitsuta** [comment]
The implementation last year was based on encrypting barcodes, which we no longer do (we instead use a separate 'search-only' UUID). At this point, for the QR code, you just scan it into the search bar and it works. So there is no barcode scanning code.

As for the scanners not working, a couple of them were not plugged in properly. This was fixed midway through the event. We could perhaps use a note on making sure new barcode scanners are plugged in really, _really_ well (if you've done it right, you should no longer be able to remove the cords without a tool). And yeah, we need more! Reg was kinda budget-limited and last year was basically a 'test run' of all this stuff.

The email for check-in codes already exists and is called "Check in faster at EVENT_NAME". So that just needs to be approved if and when we order the other barcode scanners. The only thing that happens besides that is the QR code will be displayed on the attendee's confirmation page as long as `use_checkin_barcode` is set to True. In configspec.ini it's true by default, so that should really be changed.
