### ISSUE TITLE
Registration confirmation page shows that attendee owes money for food, even though they should have free reg & food

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2502]
Ping me for attendee details to help track this down.

https://magstock7.uber.magfest.org/uber/preregistration/confirm?id=XXX
![screen shot 2017-05-24 at 11 48 53 am](https://cloud.githubusercontent.com/assets/2592431/26412631/6caa5d9a-4077-11e7-884a-2e6e0296ef7c.png)

https://magstock7.uber.magfest.org/uber/registration/form?id=XXX
![screen shot 2017-05-24 at 11 50 54 am](https://cloud.githubusercontent.com/assets/2592431/26412643/72c28374-4077-11e7-83a1-afd77224fabd.png)
![screen shot 2017-05-24 at 11 51 14 am](https://cloud.githubusercontent.com/assets/2592431/26412656/79346434-4077-11e7-8030-60e1341e5ab5.png)

**Comment by kitsuta** [comment]
Yeah, there's two pain points here:

1. There's no good way to comp extras. This includes kick-ins, but it also includes any 'extra item' that we add via plugin (like the food). The 'doesn't need to' box really only covers whether or not the attendee needs to pay for their badge.
2. The "payment" box is hidden if you're on "doesn't need to" AND there's no kick-in level. That makes it a pain to do what we want to do to get around problem 1, which is to tell the system they already paid for their extras (in this case, $25). This is an easier bug to fix, since we would just need to make the 'amount paid' box show if the attendee has any extras at all.

Realistically, we usually want to comp badges but allow the attendee to add on extra kick-ins and such and then pay for them. So most of the behavior here is fine... just, there really ought to be a way to indicate an arbitrary comped amount, or something.

The process to get the page to stop asking for money then is going to be:
1. Give the attendee a kick-in level. Save.
2. In the "Paid" box that appears after you save, enter "25" to 'comp' the amount for food.
3. Set the attendee's kick-in level back. Save.

Even though the 'paid' box won't show up anymore, the system doesn't blank it out or anything, so that should work.

**Comment by Hachi05** [comment]
Wow Vicki, you rock. Should I have the staffer follow that procedure you just laid out?

**Comment by kitsuta** [comment]
Yup! And, uh, let me know if I'm wrong. :P

**Comment by Hachi05** [comment]
That did it!

**Comment by Hachi05** [comment]
Still need this issue open to eventually make an enhancement/bugfix! <3

**Comment by earl7399** [comment]
Doesn't this method effectively say we got money that we didn't get? If it
does, I wonder how the money folks feel about it...

--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by Hachi05** [comment]
Also seems to deal with https://github.com/magfest/magstock/issues/68 where Staffers should always have free food.

**Comment by kitsuta** [comment]
Whoops, good point! Staffers probably DO get free food automatically, just the checkbox still appears which is confusing.

**Comment by Hachi05** [comment]
Well, and the thing that asks them to pay :3

**Comment by Hachi05** [comment]
@kitsuta, I think I saw you say in #devops that you could not reproduce. Search 'pete' and check out that person -- same problem.

**Comment by Hachi05** [comment]
Also I guess we need a way to give someone free food.

**Comment by kitsuta** [comment]
Oh wow, that's super interesting! It looks like you can mark someone as paying for food, then change their badge (or group, in that last case) so they get free food, and it never unmarks them as owing money for food.

I've fixed that for the badge you mentioned and I know of a code fix so that it's not a problem for MAGStock anymore. Although, yes, having a way to just mark people as getting free food would be nice.
