### ISSUE TITLE
Include Department with Shift on Shift Signups Page

### ISSUE THREAD

**Issue by Hachi05** [magfest/ubersystem#2506]
So like, Overwatch (General Support) or Registration Supervisor (Registration)

![image](https://cloud.githubusercontent.com/assets/7577129/26527058/bc41d308-4359-11e7-97c8-fb8796a61155.png)

**Comment by kitsuta** [comment]
Ooh, very good point.

By the way, if an issue would also apply to other events, you don't need to prefix it with "MAGStock 7." I'll be taking that out of the issue titles so that we know the issues are more general -- otherwise I might mistake these issues as being low priority after MAGStock is over, especially while just browsing issues by title looking for things to work on.

**Comment by Hachi05** [comment]
totally! I will not do that again.

is it possible to roll out a change to address this issue over the next day or two? if not, I totally understand -- hoping to have it for volunteers signing up :)
