### ISSUE TITLE
Labs Automated Email Date Change (Last one, I promise!)

### ISSUE THREAD

**Issue by outlaw-josiah** [magfest/ubersystem#2690]
Reminder to sign up for MAGFest Laboratories hotel room space: 7/19/17-7/22/17
Last chance to sign up for MAGFest Laboratories hotel room space: 7/22/17-7/24/17

**Comment by outlaw-josiah** [comment]
If possible, can we also change room-date-deadline to 7/28/17?

**Comment by RobRuana** [comment]
Yep, getting on that in a hot second!

**Comment by RobRuana** [comment]
Okay, all of these dates are relative to the `room_deadline` variable. So that's the only thing I can change (without a substantial time investment) that won't mess up the other events.

If I set the `room_deadline` to  7/28/17, then the dates become:
Reminder to sign up for MAGFest Laboratories hotel room space: 7/14/17-7/26/17
Last chance to sign up for MAGFest Laboratories hotel room space: 7/26/17-7/28/17

Is that close enough?

I could set the `room_deadline` to  7/24/17, then the dates become:
Reminder to sign up for MAGFest Laboratories hotel room space: 7/10/17-7/22/17
Last chance to sign up for MAGFest Laboratories hotel room space: 7/22/17-7/24/17

Or I could split the difference and set `room_deadline` to  7/26/17, then the dates become:
Reminder to sign up for MAGFest Laboratories hotel room space: 7/12/17-7/24/17
Last chance to sign up for MAGFest Laboratories hotel room space: 7/24/17-7/26/17

**Comment by outlaw-josiah** [comment]
The first change you suggested works well. I'm mostly concerned with
setting the reqest deadline earlier, and that's the one that gels most with
stops' needs.

**Comment by RobRuana** [comment]
Done and done!
