### ISSUE TITLE
Total group price auto-recalculation not correct

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#3019]
It looks like this is somehow caused by the unassigned attendee's base badge price being used to calculate the amount owed when the unassigned attendee is claimed.

In the case we're seeing on production, the group of 8 attendees paid $600 ($75 per badge). When the unassigned badges were claimed the amount owed went down by $16 each time ($75 - $59 base badge price == $16).

**Comment by RobRuana** [comment]
We will also need to resave all the group badges in the system so their amount owed is corrected.

**Comment by kitsuta** [comment]
The original unassigned badges had the correct base_badge_price of $75. It looks like what is happening here is that, DESPITE the fact that we attempt to preserve the base_badge_price when the badge is claimed, we are actually recalculating it for some reason.

This is gonna take some looking into. :\

**Comment by RobRuana** [comment]
This might have to do with the changes I made where we re-use the same attendee, instead of deleting the attendee and creating a new one. (That was to fix the unique constraint violation bug)

**Comment by kitsuta** [comment]
I think this line is actually the culprit:
https://github.com/magfest/ubersystem/blob/master/uber/site_sections/preregistration.py#L433

It's set to `restricted`, which means that admin_only attributes -- like the base_badge_price -- will fail to save over.

**Comment by kitsuta** [comment]
Of course you added that line while making that change, so yes, you're right. :)

It looks like fixing it will be pretty simple, then. Retroactively fixing the data, however... 😰

**Comment by RobRuana** [comment]
Resave groups?

**Comment by kitsuta** [comment]
The only way to preserve that price is DURING the process of claiming the badge. Resaving the groups won't do anything -- the base_badge_price is already set to an incorrect value.

**Comment by kitsuta** [comment]
Also, due to that bug, NONE of the restricted parameters were being transferred, which in this case means:
base_badge_price
badge_num
ribbon
paid
overridden_price

So any solution we come up to fix this data would, ideally, also fix those columns. If we can think up something at all. It's pretty confusing, because the history for the badges makes it still look like we were creating new badges...?

**Comment by kitsuta** [comment]
It looks like, in addition to or possibly instead of that `restricted=True` being the culprit, the group in this specific actually dropped badges before adding them. When dropping a badge, we DO still remove the old badge and add a new one, and the only things that get transferred to the new unassigned badge are the badge type, ribbon type, registered date, and paid status. That line is here: https://github.com/magfest/ubersystem/blob/master/uber/site_sections/preregistration.py#L483
