### ISSUE TITLE
Decide upon and implement on-site policy for underage volunteers

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#371]
Uber currently unsets volunteer status for any attendee under 18.  This is theoretically in line with our policies, though we do occasionally special-case allowing underage volunteers, so we should decide whether this is okay and implement whatever the updated policy is in the Uber codebase.

**Comment by bds002** [comment]
I know we hacked around this one for awhile... - Is there a new issue to be references to?
@EliAndrewC @kitsuta 

Currently I don't think we let (or Uber let's) Under age preregistered attendee be marked as Volunteering.  I think Uber was updated so that we can allow it on site with Admin approval (Stops sign-off) with notes (They get attendee badge with Volunteer ribbon)-  The three exceptions I know of for M13 where:
--- the younger brother of a Staff member :(Jorem brother of Foxx) Jorem has staffed other Cons and had experience. I know the family and OK'd if from STOPS standpoint, he found a home in Con Suite. 
--- Younger son of Staffers on Con Suite - (Minor Family entire family was here to staff and he helped). Jenny True talked to me about this one before Fest and it was also cleared as a family thing for the Minor family. 
--- Little Joey - Fat Chris's son, but I believe we actually had a staff badge for him as a special addition?

**Comment by EliAndrewC** [comment]
The issue is that instead of getting an error message when you check the "Volunteering" box, the system just unsets an underage person's volunteering status without any kind of warning that it did that.  This ends up being super confusing.  So it's fine if we keep the same policy we've had before, it should just be more obvious, because we've had several cases where someone said, "Hey this seems broken I keep checking the checkbox but it doesn't get saved."

**Comment by bds002** [comment]
So this issue has reared up again, we have a Minor that was Attendee Volunteer for M13, became a staffer for MAGFest 2015, worked enough hours and is qualified as a staffer for M2016.  When I try override his Minor badge to be a Staff Badge, I get a Minor Badge with a preset number.  I don't think this is the intended result.

![capture](https://cloud.githubusercontent.com/assets/8822346/18634709/3ba7b4b6-7e50-11e6-8cdb-41e2cceb19a1.PNG)

I am at a lost as to explain the best way forward here. @EliAndrewC and @kitsuta

**Comment by earl7399** [comment]
It seems like the simple solution would be to add a Volunteer ribbon to
their badge until a better solution is coded.


--
Robert Earl <r.a.earl@gmail.com>
FAX: 1-440-919-5086

**Comment by kitsuta** [comment]
Oops.

Yeah, this is happening from an automated adjustment that the /magprime repo does to one's badge type AND one's ribbon based on one's age.

@earl7399's proposed solution won't actually work, because they're assigned a ribbon to denote that they're over 13.

Technically this is a totally different bug, which I'll file in the magprime repo and get around to fixing, er, soon. I hope.
