### ISSUE TITLE
Implement banned staffer list

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#372]
We currently have a config option for banned staffers, but there's nothing that actually checks it.  We should do this before we start letting people sign up for shifts.

**Comment by bds002** [comment]
This should probably be tagged - before next year- since Shift Signups in progress and M13 is quickly approaching.   I would like to look at the priority level of this since we have multiple coders now.

For M13 we have had 2 cases of staffers that we have banned because of 1 issue or the other that tried to come back to us through our Contract groups, or other groups of friends coming to staff new areas.

**Comment by EliAndrewC** [comment]
That work is already in a ticket tagged "soon": https://github.com/magfest/ubersystem/issues/343

Unfortunately, like many things it's been about number 2 or 3 on my priority list for the past couple of week,s and new stuff has come in faster than I can clear it :(

I agree that this needs to get done before MAGFest.  Ideally in the next few days, but I can't guarantee that.
