### ISSUE TITLE
If amount paid on a group is greater than amount owed, the pay button will appear on the group management page

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#411]
Likely caused by the comparison between amount paid and amount owed being "not equal", rather than "less than"

**Comment by Lusarien** [comment]
Hey was browsing through the issues and came across this, since issue 421 is fixed is this also fixed? Let me know thanks!

**Comment by kitsuta** [comment]
No, we left them both open because they're not actually related in the code. They were just noted as related because they were found at the same time. :)

Specifically, I'd expect that somewhere there's a check for `if group.amount_paid == group.amount_owed` - however, the check fails when the group has paid _more_ than they owe, and we only want to show the pay button when they've paid less.

**Comment by EliAndrewC** [comment]
Confirmed fixed in latest master.
