### ISSUE TITLE
from room assignment page, say if a volunteer who isn't directly added to a room, is approved

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#59]
---------------------------------------
- Bitbucket: https://bitbucket.org/EliAndrewC/magfest/issue/60
- Originally Reported By: [ ](http://bitbucket.org/hachi05)
- Originally Created At: 2013-12-02T06:17:56.496

**Comment by bds002** [comment]
I don't really understand what is being asked here, it's a carry over ticket from the bitbucket days... now 18 months old and we have re-done how hotel staff rooms are done since then.  It looks like Hatchi Matt added it back then, I would say close it since we are looking at modifying Hotel Staff rooms again.

**Comment by kitsuta** [comment]
Yeah, I'll close it in the interest of making our issues more manageable.
