### ISSUE TITLE
Duplicate Staff badge numbers being issued in Uber

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#674]
There is a staffer: Kevin Sonney With badge number 330.  He had been assigned #321. I moved him to 330 to fall within a group of pre-assigned badges for Dorsai. Subsequently Uber when renumbering badges has issues 2 of the same number.   Currently there are 2 Staff #317 badges assigned.

**Comment by kitsuta** [comment]
Badge numbering code has been completely rewritten since the last comment on this issue.

We actually had the range cap out at Anthrocon - instead of stomping over the next range as it used to, the current version of the system simply assigned the last number in the range to every new badge. This is actually pretty good behavior, because it's very obvious what's going on to anyone who looks and relatively simple to fix. Because of that, I'm closing this issue.
