### ISSUE TITLE
Make sure not to trash any badge names with unique characters

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#815]
Some of the printed badge names people have entered have non-standard characters, like ♪. We need to make sure nothing in the process for badge printing turns these characters into junk.

This is a three-step process:
1. Make sure the CSV export doesn't trash the characters
2. (non-uber) Make sure the printer company is actually capable of printing those characters
3. (next year) Make ubersystem only accept characters that won't cause an issue

**Comment by EliAndrewC** [comment]
The above badges were emailed to the badge printing folks to see i they were a problem a week ago.  I'm tagging this with "next year" so that we don't forget about having a better system if it turns out that we don't support this stuff.

**Comment by RobRuana** [comment]
Any update on this? Did those badges cause any issues?

**Comment by ShevaDas** [comment]
@RobRuana I can say with absolute certainty that whether or not these badges caused issues, badges with cutesy names like these at Super/West/Labs have caused me big problems this year and last (see also #2761 made for handling this use case).

My strong preference for resolving this issue is to restrict the badge name field to only the set of printable ASCII characters (not extended). The character set we can technically use varies each year depending on the font the badges are printed in, and it's a huge timesink to manually edit badge names because a font does or doesn't include special characters or has a really weird set of characters or whatever.

**Comment by kitsuta** [comment]
Just to confirm, is this what you want?
```
'0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ \t\n\r\x0b\x0c'
```

That's the output of Python's `string.printable` method, which is (supposedly) all printable ASCII characters. Or do you think it should be more limited than that? I can definitely see chucking out all the whitespace characters (all the stuff after `\t`) but is there anything else you want to restrict?

**Comment by ShevaDas** [comment]
With the removal of the whitespace characters, that looks sane to me. Although it may happen that, as with Super last year, we use a font that doesn't include most or all of `!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~`, hopefully that's a rarity.
