### ISSUE TITLE
Groups' "amount owed" is wrong

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#965]
At https://prime.uber.magfest.org/m13/groups/index - most of the groups who have paid have an "amount owed" as $0. It should be equal to the amount they needed to have paid, not how much they have left to pay.

**Comment by EliAndrewC** [comment]
Ah, whoops.  Good catch, it's definitely using the wrong property there.

**Comment by kitsuta** [comment]
Do we want to show their total cost on this page or the amount_unpaid?

**Comment by EliAndrewC** [comment]
Hmm, actually showing all three might be good.  So get rid of "Owed" and have three columns: "Total Cost" / "Amount Unpaid" / "Amount Paid".

I deliberately got rid of the ``amount_owed`` property this year since it was confusing whether it refered to the total cost or the amount unpaid.  So we probably shouldn't use the word "owed" in the website copy either for the same reason.

**Comment by kitsuta** [comment]
Yeah, that makes sense for sure. Consider it done.
